open-horizon/anax

agreementbot/activecontracts.go, agreementbot/build/Makefile, agreementbot/governance.go, exchange/rpc.go
1. Device API URL missing from agbot agreement status in exchange. Fixed that in gov when finalized state is set.
2. Gov cancelled agreement while it was being formed. Fixed that so that it only scans for db records with formed agreements.
3. Data verification should have been checking for specific agreement ids with the backdoor prefix, not any agreement id with a backdoor prefix.
=> also fixed dv bug and gov bug

policy/api_spec_list.go, policy/api_spec_list_test.go, policy/policy_manager.go, policy/policy_manager_test.go
1. Find policy by API Spec URL, complete and tested.
2. Delete policy by Spec URL, created but returns "not implemented" error. Will take a lot more work complete.
=> find by api spec URL

agreement/agreement.go, agreementbot/agreementbot.go, agreementbot/build/Makefile, config/config.go, exchange/rpc.go, governance/governance.go
1. Updated agbot to exploit secondsStale filter on device search API
2. Found and fixed a bug where anax doesnt pick up its device token from it's db when it restarts.
=> exploit new seconds stale on search

agreement/agreement.go, agreementbot/activecontracts.go, agreementbot/agreementworker.go, agreementbot/persistence.go, citizenscientist/protocol.go, config/config.go, policy/data_verification.go, policy/data_verification_test.go, policy/policy_file.go, policy/policy_file_test.go, policy/test/pfcompat2/expecting.policy, policy/test/pfcompat2/merged.policy, policy/test/pfcreate/created.policy, policy/test/pfcreate/expecting.policy, policy/test/pfmerge1/expecting.policy, policy/test/pfmerge1/merged.policy, policy/test/pftest/echo.policy, policy/test/pftest/test1.policy, policy/workload.go, policy/workload_test.go, vendor/vendor.json
See US 431 for a description of changes:
https://projects.hovitos.engineering/project/rmlinden-mtn-edgenet-v2/us/431
Briefly, this support allows a workload deployer to specify a password (in the policy file) that the workload uses at runtime to authenticate with its cloud ingest when the workload is running.
=> workload password hash passed to workload

agreementbot/agreementbot.go, agreementbot/governance.go, config/config.go, policy/data_verification_test.go, policy/policy_file.go, policy/policy_manager.go
1. In agbot split the protocol message timeout from the blockchain timeout.
2. Also fixed a bug (found while testing the timeout split) that occurs during agbot restart where false policy differences are detected causing all agreements to be killed and recreated.
=> also fixed a policy comparison bug

agreement/agreement.go, agreementbot/agreementbot.go, agreementbot/agreementworker.go, agreementbot/governance.go, exchange/rpc.go, governance/governance.go
When persistence was added to the exchange, they had to change the interface to PUT /devices/{id} such that we could no longer pass a blank token in the body to indicate that we didnt want it to be updated.
While we were in this area of the code, we noticed that device token could be passed in the HTTP basic auth header instead of as a URL parameter, so we made that change as well.
=> always pass token in PUT device body

agreement/agreement.go, agreementbot/agreementbot.go, agreementbot/agreementworker.go, agreementbot/governance.go, citizenscientist/protocol.go, ethblockchain/blockchainworker.go, ethblockchain/connection.go, ethblockchain/connection_test.go, ethblockchain/event_log.go, ethblockchain/event_log_test.go, ethblockchain/rpc.go, ethblockchain/rpc_test.go, events/events.go, governance/governance.go, persistence/persistence.go
The only way to get the agbot reason code is to consume events from the blockchain transactions. That's what the event_log is for. This is the same code that runs at the heart of the smart contract monitor.
=> propagate agbot reason code to device

agreement/agreement.go, agreementbot/agreementbot.go, agreementbot/agreementworker.go, agreementbot/governance.go, governance/governance.go
1) When the exchange goes down, retry logic logs the wrong variable causing a panic in go.
2) Changed the syncOnInit logic in device and agbot such that it doesnt hold up init when the exchange is down.
=> fixed anax panic when exchange goes down

agreement/agreement.go, agreementbot/agreementbot.go, agreementbot/agreementworker.go
This change makes use of the configured URL less brittle, esp. b/n the UI and Anax.
Diffs also include go fmt changes to edited files.
=> replaced string concat for path building with path.Join() so config param needn't include a trailing slash

agreementbot/agreementbot.go, agreementbot/agreementworker.go, agreementbot/commands.go, agreementbot/governance.go, agreementbot/lock_manager.go, agreementbot/lock_manager_test.go, config/config.go, events/events.go, policy/policy_file.go, policy/policy_file_test.go, policy/policy_manager.go, policy/policy_manager_test.go, policy/workload.go
Fixed issue 202 so that I could test.
Added unarchived filters to database searches in agbot. This was missed in the agbot/api feature.
Added a small bit of code to support multiple agreement protocols in the agbot. This was needed in order to properly react to a new policy with a new agreement protocol in it.
Most of the code is in support of dynamically adding/modifying policies int he agbot.
=> issue164 - dynamic policy in the agbot

Makefile
This install target is deb friendly: the deb packaging process doesn't create the install directories ahead of time so the `install` make target should. This also improves the target by:
- Removing the dep on building (this is the standard; it's less safe for a user but won't duplicate work in some build processes)
- Deleting git and other metadata from contract repo before publishing
=> Deb-friendly install target

Makefile
If desired, create the file `rules.env` in the project root before building to get custom environment settings.
Also optional is the new `GOPATH_CACHE`:
make all GOPATH_CACHE=$GOPATH/.cache
This enables reusing previously downloaded external dependencies without requiring that you put the project in your `GOPATH`. The speed up and bandwidth savings are significant.
=> added optional env source and gopath cache features

cli/cliutils/cliutils.go, cli/hzn.go, cli/importkey/importkey.go, cli/register/register.go, cli/samples/more-examples.json, cli/show/show.go
- Detect if already in the middle of registration when hzn register is run
- Give good msg for several show cmds when not registered yet
- Support reading input file from stdin
- Support HTTPSBasicAuthAttributes and AgreementProtocolAttributes
- Added more error checking
- make node id optional (get it from GET /horizondevice) and node token optional (generate random toke)
=> Make hzn register reentrant

Makefile
Just commented out the placement of the default UI page when anax install target is used. This is temporary until issue 62 in the deb packager project is resolved.
=> disable default Horizon UI page

cli/agreement/agreement.go, cli/attribute/attribute.go, cli/cliutils/cliutils.go, cli/exchange/microservice.go, cli/exchange/node.go, cli/exchange/pattern.go, cli/exchange/workload.go, cli/hzn.go, cli/metering/metering.go, cli/node/node.go, cli/register/register.go, cli/samples/insert-workload-into-pattern.json, cli/samples/microservice.json, cli/samples/minimal.json, cli/samples/pattern.json, cli/samples/workload.json, cli/service/service.go, cli/workload/workload.go
- changed all 'hzn exchange' cmds to use -u creds instead of -n
- added short flag -N for --names-only
- added signing of ms, workload, pattern for the case in which the images are stored in a docker registry
- supported optionally getting exchange url from HORIZON_EXCHANGE_URL_BASE
- added patter insertworkload
=> Add ms wk to hzn

cli/attribute/attribute.go, cli/exchange/agbot.go, cli/exchange/microservice.go, cli/exchange/node.go, cli/exchange/pattern.go, cli/exchange/workload.go, cli/hzn.go, cli/register/register.go
- make --names-only the default behavior for exchange list cmds, remove --names-only|-N flag, and add --long|-l instead
- add hzn exchange pattern removeworkload sub-cmd
- add instructions at the end of ms/wk publish to docker push
- have node create check if node is owned by another user
=> Hzn usability

Makefile
This fixes an occasional problem Bruce once mentioned and I have hunted a few times.
=> added Makefile target deps on gopathlinks so we avoid bash errors trying to use TMGOPATH or PKGPATH before setting it up

cli/agreementbot/agreement.go, cli/cliutils/cliutils.go, cli/exchange/microservice.go, cli/exchange/pattern.go, cli/exchange/workload.go, cli/hzn.go
- added env vars HZN_ORG_ID, HZN_EXCHANGE_USER_AUTH, and HZN_EXCHANGE_API_AUTH that can be defaults for flags -o, -u, -A, respectively
- changed env var name HORIZON_EXCHANGE_URL_BASE to HZN_EXCHANGE_URL (to be consistent with hzn dev)
- changed HORIZON_URL_BASE to HORIZON_URL
- added optional org field in ms/wk/pat input json and checked that (if specified) it equals the org they are putting it into
- changed the deployment/deployment_overrides field of the ms/wk/pat input json to be regular json, instead of an escaped string
=> added env vars, and a regular deployment field

cli/dev/dependency.go, cli/dev/microservice.go, cli/dev/microservicedefinition.go, cli/dev/userinput.go, cli/dev/utils.go, cli/dev/workload.go, cli/dev/workloaddefinition.go, cli/hzn.go, cli/register/register.go
For hzn dev based projects, removed dependency.definitions.json and moved all project dependencies into dependencies directory.
=> rework dependency model for hzn dev

cli/cliutils/cliutils.go, cli/exchange/agbot.go, cli/exchange/microservice.go, cli/exchange/node.go, cli/exchange/pattern.go, cli/exchange/service.go, cli/exchange/version.go, cli/exchange/workload.go, cli/hzn.go, cli/key/key.go, cli/register/register.go, cli/wiotp/wiotp.go
- 'hzn key list' was returning null when there are no cert-keys - fixed
- when publishing pre-signed ms/wl/svc, don't print that we are signing it
- document env vars in the help of -u, -A, and -o flags
- allow an exchange id to be passed in prefaced by the org (like it is displayed in list)
- add 'hzn exchange version' sub-cmd
=> fix empty key list, add exch version, allow exch id prefixed by org

cli/exchange/pattern.go, cli/hzn.go, cli/key/key.go, cli/register/register.go, cli/samples/insert-service-into-pattern.json, cli/samples/pattern-workloads.json, cli/samples/service.json, cli/service/service.go
Fixed:
- `hzn exchange service publish` and could not find /usr/horizon/samples/service.json file.
- `hzn exchange pattern publish` does not work for service based. And the sample file does not show the how to put services in the pattern.
- `hzn exchange pattern list` does not work for service based patterns.
- `hzn exchange pattern verify` does not work for service based patterns.
- `hzn register` does not work for service based if there is input file.
- `hzn service list` and `hzn service registered` do not show anything
=> More hzn service support

api/container.go, api/output.go, api/path_service.go, api/path_workload.go, container/container.go, ethblockchain/blockchainworker.go, events/events.go, governance/governance.go, governance/microservice.go, microservice/microservice.go, microservice/microservice_test.go, persistence/microservices.go, persistence/microservices_test.go
Supports sharable=multiple for dependency trees where the service is referred to more than once.
Also fixes the GET /service output in the instances section to properly display containers for agreement services.
=> Issue 444 - Support sharable=single services

agreementbot/agreementbot.go, agreementbot/consumer_protocol_handler.go, cli/dev/utils.go, cli/dev/workload.go, exchange/rpc.go, governance/governance.go, governance/microservice.go, persistence/attributes.go, persistence/persistence_int_test.go, policy/policy_file.go
Support manual policy files with "services only" for citizen scientist use cases. There is no more support for workloads and microservices with manual policy files.
=> Issue 444 - re-enable the citizen scientist use cases

Makefile, anax-in-container/README.md, anax-in-container/service/anax.service, anax-in-container/service/bluehorizon-env.sh, cli/dev/dependency.go, cli/dev/utils.go
- fixed 1 case in which `hzn dev service start` was looking at `workload.definition.json`
- anax-in-container improvements:
- added sigterm catching to unregister before the container goes down
- improved how `/etc/wiotp-edge` and `/var/wiotp-edge` are handled on mac. This enabled `hzn dev` to run services that use core-iot on mac.
- the anax container now creates the wiotp certificate if it is passed the token on `docker run`
- added a mode in which the anax container can be run to only create the wiotp certificate, and then will exit. This is in support of `hzn dev`
- the make target now uses a version that is intended to match horizon's version. And it will also be tagged as `latest`, so users can more easily use it.
=> improvements to anax container

container/container.go, ethblockchain/blockchainworker.go, events/events.go
In container/container.go function NewContainerLaunchContext()
is called with nil as last parameter which causes nil pointer
dereference.
This commit changes the stored value to pointer to fix this issue.
=> nil pointer dereference fix

externalpolicy/text_language/text_language.go, externalpolicy/text_language/text_language_test.go
This PR is for first 2 items of issue 892 and unit test:
- Support version, integer, float, string, boolean and list of string types (Lily)
- Support boolean operators and aliases (&&, ||, etc) in the constraint language
=> issue892 - added validation for constraints

cli/exchange/agbot.go, cli/exchange/node.go, cli/exchange/pattern.go, cli/exchange/service.go
Allow all 'hzn exchange _____ list' commands that take '\<org\>/' as an argument to also take '\<org\>/*'
=> Issue #986 - '--long' flag not working for hzn exchange pattern list

cli/exchange/business.go, cli/exchange/service.go, cli/hzn.go, cli/policy/policy.go
For issue 980:
1. `hzn policy new` will show node policy template:
2. `hzn exchange business new` will show business policy template:
3. `hzn exchange service newpolicy` will show service policy template:
=> Issue 980 - Provide node policy author a way to get a skeletal node policy

cli/exchange/catalog.go, cli/hzn.go
1. For catalog servicelist
- `hzn exchange catalog servicelist -s`
- `hzn exchange catalog servicelist`
- `hzn exchange catalog servicelist -l`
- `hzn exchange catalog servicelist -s -l`
2. For catalog patternlist
- `hzn exchange catalog patternlist -s`
- `hzn exchange catalog patternlist`
- `hzn exchange catalog patternlist -l`
- `hzn exchange catalog patternlist -s -l`
=> Issue 891 - hzn sub-cmd to display services in all IBM-type orgs

cli/exchange/service.go
The ServiceAddPolicy function will now work with a service that does not have the organization name prepended.
=> Fixed a small bug in serviceaddpolicy

externalpolicy/property_list.go
There are also some error message changes so that messages referencing the runtime type will show the runtime type correctly.
=> Add explicit validation for property declared types

Makefile, css/image/cloud-sync-service-amd64/Dockerfile
Runs the CSS in the container as a non-root user.
note: This will require the css to listen on a port above 1024 as this is a requirement to run as non-root.
=> Convert CSS container to run as non-root

api/api_node.go, api/path_node_userinput.go, test/gov/gpstest_apireg.sh, test/gov/pws_apireg.sh
When service does not exist in the exchange:
When given an userinput variable that doesn't define in the service, show a warning message in log but still save the userinput:
When given a wrong type of userinput variables, show errors:
Support for list of strings:
Warning log updated:
=> Issue 1074 -  hzn userinput add/update should verify the user input before saving it

Makefile, vendor/vendor.json
Example curl commands and results for call CSS APIs which in the running CSS container after running e2e test:
1. `curl -X GET "https://localhost:9443/api/v1/objects/e2edev@somecomp.com?filters=true" --insecure -u e2edev@somecomp.com/e2edevadmin:e2edevadminpw
` will show all the objects:
2. `curl -X GET "https://localhost:9443/api/v1/objects/e2edev@somecomp.com?filters=true&objectType=model&objectID=policy-multires.tgz" --insecure -u e2edev@somecomp.com/e2edevadmin:e2edevadminpw` will show object with objectType: model, objectID: policy-multires.tgz
3. `curl -X GET "https://localhost:9443/api/v1/objects/e2edev@somecomp.com?filters=true&destinationPolicy=false" --insecure -u e2edev@somecomp.com/e2edevadmin:e2edevadminpw` shows no results.
`curl -X GET …
=> Issue 1153 - Upgrade MMS to use latest edge-sync-service updates 0.10.4

cli/hzn.go
This one is from the kingpin framework. But it is not used in hzn. The help text for it is not able to pull out for translation for different locales. So it's better to remove it.
=> Removed version flag for hzn

api/api_node.go, api/path_node.go, api/path_node_test.go, cli/cliutils/cliutils.go, cli/register/register.go, exchange/handlers.go
Did the pattern checking for both hzn and anax api because we would like to give proper messages to the user who are using `hzn register` in some special cases.
=> Issue 783 - 'hzn register' handle node pattern defined in the exchange

cli/exchange/node.go, test/gov/pattern_change.sh
1. service does not exist
2. the variables are defined in the service, otherwise return a warning message
3. variables are correct type
4. the node is associated with a pattern `sall`, the service should be defined as top level service or as dependent service
5. 
the userinputs need to be set in given userinput.json if no default value given in service userinput.
=> Issue 1081 hzn exchange node update verify userinput

cli/deploycheck/allcomp.go, cli/deploycheck/policy.go, cli/deploycheck/userinput.go
bug 1) error returned by deploycheck when pattern org not specified in pattern id. Help text says it will use the user org in this case.
bug 2) querying the exchange with an empty node id when node id is retrieved from the node causing an error
=> Fixes for 2 small cli bugs

container/container.go, doc/deployment_string.md
Fixed an issue causing dependent services of services with network=host to fail on start up
=> Add network=host to the documentation for deployment strings

README.md
Go dependency not explicitly stated in readme
running the make as the current master branch version requires go 1.10 or higher.
=> Added note of the go dependency to the readme

Makefile, test/README.md
- make deps in the main anax file fails if $GOPATH/bin doesn't exist
Also
- remove go get govendor from anax/test readme
- add apt install build-essential to prereqs in anax/test readme to prevent issue on ubuntu where go cannot find gcc
=> Issue 1631 - anax/Makefile failure if $GOPATH/bin does not already exist

Makefile, go.mod
$GOPATH/pkg doesn't exist on a new environment when pkgdeps is skipped. This causes 'make all-nodeps' to fail
=> Issue 1635 - makefile failure on 'make all-nodeps'

agent-install/README.md, agent-install/agent-install.sh
Updates in this PR are the checked boxes in this issue:
https://app.zenhub.com/workspaces/open-horizon-5877f2c6a8ad090f31c73853/issues/open-horizon/anax/1502
- removed creation of `~/.hzn/hzn.json` for Mac around line 542 
- added usage description of `-l`
- moved agent-install.crt to `/etc/horizon` ...this had to be `/private/etc/horizon` for Mac because docker on Mac does not have access to `/etc` by default, but it does have access to `/private` which is a symbolic link to `/etc` 
- removed ` Do you want to overwrite the current node configuration?[y/N]: `
- when rerunning agent-install.sh with the same install pkgs, it won't install them, unless a force flag is specified
- /agent-install.sh -h will exit code of 0 (if the usage is shown as a result of invalid args, then the exit code …
=> Some agent-install.sh user experience improvements

Makefile
Check that $GOPATH is writable and a directory
=> Issue 1635 - horizon-deb-packager failing on mkdir /home/max/go/bin

agent-install/agent-install.sh
- fixed `grep: ": No such file or directory` issue with `netstat` command
- removed first `apt update` because it's called twice 
- skip prompts with `-b` flag  
This PR is tied to three of the issues noted in issue 1502:
https://github.com/open-horizon/anax/issues/1502
=> Agent-install.sh user experience improvements

agent-install/agent-install.sh
- accept `HZN_EXCHANGE_NODE_AUTH` with the `-a` flag, in `agent-install.cfg`, or the env var, to register a pre-created node in the exchange
=> Additions to agent-install.sh for SDO

governance/shutdown.go
After the change, the warning message is not showing
=> Issue 1697 Unregister edge cluster agent returns DockerEndpoint error

agent-install/agent-install.sh
In this fix:
- Remove -T in `hzn register ... ` command
- Keep -T "cluster" in `hzn exchange node create ... ` command
=> Fix: agent-install.sh remove -T flag in hzn register

agent-install/agent-install.sh
added device_cleanup_agent_files() to remove leftover deb packages and agent-install files when using bulk install method
**Output of the function with the following directory contents**
```
root@adonis1:~# ls
agent-install.cfg                             Dockerfile.arm    horizon_2.26.0~ppa~ubuntu.bionic_amd64.deb      release4.0
agent-install.sh                              Dockerfile.arm64  horizon-cli_2.26.0~ppa~ubuntu.bionic_amd64.deb  script.sh
bluehorizon_2.26.0~ppa~ubuntu.bionic_all.deb  examples          icpcreds                                        service.sh
creds                                         files             Makefile                                        squid
Dockerfile.amd64                              horizon           node-id-mapping.csv …
```
=> Added device_cleanup_agent_files() to agent-install.sh

cli/unregister/unregister.go, governance/governance.go
1. Fixed deep clean for cluster node.
2. Fixed unregistration hung problem when the service has dependent services. (The service has both deployment and clusterDeployment. The dependent services are for device nodes only).
=> Fixed external deep clean for cluster type upon unregister

cli/register/register.go
The output of `hzn register ...` looks like this when the node already exists:
```
Horizon Exchange base URL: https://icp-console.apps.rested-squid.purple-chesterfield.com/edge-exchange/v1
Node mycluster/bp-edge-cluster-3 exists in the Exchange
No pattern or node policy is specified. Will proceeed with the existing node policy.
Initializing the Horizon node with node type 'cluster'...
Warning: no input file was specified. This is only valid if none of the services need variables set (including GPS coordinates).
However, if there is 'userInput' specified in the node already in the Exchange, the userInput will be used.
Changing Horizon state to configured to register this node with Horizon...
Horizon node is registered. Workload agreement negotiation should begin shortly. Run 'hzn agreement …
```
=> Minor fix: removed blank like in hzn register output

agent-install/agent-install.sh
agent-install usage information:
```javascript
$ ./agent-install.sh -h
agent-install.sh <options> -- installing Horizon software
where:
$HZN_EXCHANGE_URL, $HZN_FSS_CSSURL, $HZN_ORG_ID, either $HZN_EXCHANGE_USER_AUTH or $HZN_EXCHANGE_NODE_AUTH, variables must be defined either in a config file or environment,
For agent install on edge cluster:
$IMAGE_ON_EDGE_CLUSTER_REGISTRY must be defined in a config file or environment if deploy type is "cluster", format: <registry-host>/<ocp-project>/amd64_agent (without tag), for microsk8s: localhost:32000/agent-repo/amd64_agent
if set $EDGE_CLUSTER_STORAGE_CLASS in environement, the value of "EDGE_CLUSTER_STORAGE_CLASS" in configuration file will not be used
Parameters:
-c          - path to a certificate file
-k          - path to a configuration …
```
=> add more info in agent-install.sh usage and Issue 1846

pkg/rpm/horizon-cli/Makefile, pkg/rpm/horizon-cli/horizon-cli.spec, pkg/rpm/horizon/Makefile, pkg/rpm/horizon/horizon.spec
Removed usage of symlink to prefix source files with package name and instead used %setup -c in spec file to accomplish the same for horizon and horizon-cli.
=> Fixed RPM build on Linux hosts

Makefile
Made EXECUTABLE static and equal to 'anax' to prevent the binary name from changing when the directory Anax is built in changes. If the binary name is supposed to change for some reason, then obviously this won't work and you can reject the PR. But I didn't see anywhere in the code where that would happen.
=> Change EXECUTABLE to anax instead of dirname 

pkg/deb/Makefile
This is a workaround so that deb packaging will work for non-amd64 architectures. Since the build occurs on amd64 hosts (for all architectures), the main Anax Makefile will not generate the hzn_bash_autocomplete.sh script because the binary won't work on that system. When we get to the debpkgs target, this cp command will will fail since the script doesn't exist. This means that arm64, armhf, and ppc64el architectures **will not have hzn_bash_autocomplete capabilities**.
=> Fixed missing bash completion script throwing error

test/Makefile, test/README.md
Fixes 'no such host' errors for hosts not in existing DNS when doing e2edev testing against remote hosts. Fixes #1958.
=> Issue 1958 - Add the --add-host flag to the Docker run command in e2edev remote testing

Makefile
**Description of the change:**
I unset the GOPATH variable prior to running `go mod vendor` in the `i18n-catalog` makefile target. This was inspired by the following StackOverflow answer: https://stackoverflow.com/a/62062562/8907.
Signed-off-by: bencourliss <bencourliss@ibm.com>
=> Issue #1991 - Fixed issue with building i18n-catalog 

Makefile, pkg/rpm/horizon-cli/Makefile, pkg/rpm/horizon/Makefile
fix rpm building for centos/fedora/rhel in aarch64 and ppc64le
fix for issues: #1971   #2050 
Signed-off-by: Gavin Gao <gavingao@cn.ibm.com>
=> Issue 1971 & Issue 2050 – fix rpm building for centos/fedora/rhel in aarch64 and ppc64le

.gitignore, agent-install/test/assertions.sh, agent-install/test/common.sh, agent-install/test/test.sh
Updated test suite that works with new changes to agent-install.sh. Includes the following:
- Updated to pull packages from artifactory instead of pkg-bluehorizon
- Removed 2 test cases for no longer supported cases (down-level agent installation support removed from agent-install.sh)
- Removed redundant assertions that could cause failures and test inconsistency (waiting for services to start when not necessary).
- Added support for local package use for tests that require only one version (all but test 6)
- Added support for only downloading a current version and skipping the agent-upgrade test (test 6). This test will run if a current version and previous version are provided to download.
- Added help menu to give some help context outside of git
- Fixed several test cases that failed …
=> overhaul for new agent-install.sh tests and general test improvements

tools/no-debug-pkg
This PR fixes version ID matching at no-debug-pkg script. Affects external linking mode switch on RHEL platform builds, that omits debuginfo packages and the corresponding rpmbuild breakdown on RHEL.
Resolves #2096
=> Issue 2096 - Fix no-debug-pkg versions issue

pkg/rpm/horizon-cli/Makefile
**Description of the change:**
Added trailing slash to `cp` commands so it would not try to replace a directory with a file. Also separated the `mkdir` command to not use `{}` syntax which seems problematic on some Linux hosts.
Signed-off-by: bencourliss <bencourliss@ibm.com>
=> Issue #2117 - Fixed issue with building horizon-cli RPM on Linux hosts

README.md
The reference link of the `README` can't be accessed, because the files have been moved from the `doc` to `docs`
=> Fix the reference link error

externalpolicy/text_language/text_language.go, externalpolicy/text_language/text_language_test.go
1. Modify "OpenParen" and "CloseParen" EBNF grammar to handle cases that no/one/many whitespaces are around parentheses . 
2. Add a new test case for the modification.
Signed-off-by: H.Gao <h.gao1@tue.nl>
=> Issue #2130 - constraint parsing failed when the closing round bracket has a space before it

agent-install/agent-install.sh
Added 8.3 for testing and tech preview purposes in the future. Today this will only run with docker native on RHEL 8.3.
=> added 8.3 to enable testing, tech-preview in future

cli/exchange/service.go, cli/hzn.go
This commit addresses #2211. This adds a flag to the `hzn exchange service publish` that sets the `public` field of the service to either be true or false based on the chart below. The rules are as follows.
1.  If the `hzn exchange service publish` has the flag set, then it takes precedence
2. Otherwise, `public` defaults to whatever is set in the metadata ie `horizon/service.definition.json`
3. If both are undefined, set to `public` to false
Tested by locally building hzn cli and making sure that running `hzn exchange service publish` follows the results above.
Signed-off-by: Clement Ng <clementdng@gmail.com>
=> Issue 2211 - Add public flag to hzn exchange service publish

test/Makefile
The e2edev-agbot container does not bind the local host's .docker to the container's /root directory. It does so for the /home/agbotuser. Added a volume bind to fix this. Will require rebuilding the e2edev-agbot container prior to running the tests.
=> Issue 2272 - Fix to use authenticated Docker user for e2edev tests

cli/dev/servicedefinition.go, cli/dev/utils_int_test.go, test/gov/hzn_dev_services.sh
This commit partially addresses this [open-horizon/examples issue](https://github.com/open-horizon/examples/issues/356). Services should be created with `"public": false` so those outside the organizations can't see them by default.
Tested by locally building the hzn cli and making sure that the resulting horizon files have `"public": false` set on them.
Signed-off-by: Clement Ng <clementdng@gmail.com>
=> Fix "hzn dev service new" command to publish services with "public":false

agent-install/agent-install.sh
7.9 was missing from the REDHAT supported versions
=> 7.9 missing from REDHAT versions

container/container.go
=> Issue 2333 - Modify --device docker command to accept non ':' paths

Makefile, anax-in-container/Dockerfile.ubi.arm64, anax-in-container/horizon-container, anax-in-k8s/Dockerfile.ubi.arm64
I added basic arm64 support to anax-in-container and to anax-in-k8s. See also #2337 and #2324
For a full arm64 anax-in-k8s support the file agent-install/agent-install.sh needs to be also modified. See also #2327 and #2326
=> Issue 2237 2324 - Added arm64 support to anax-in-container and to anax-in-k8s

agent-install/agent-install.sh
See #2438 for details and my proposed fix.
=> Issue 2438 - agent-install.sh doesn't recognize "k3s kubectl" correctly due to a if/elif block sequence order problem

test/Makefile, test/README.md, test/docker/Dockerfile, test/docker/fs/etc/vault/config.json, test/gov/gov-combined.sh, test/gov/vault_test.sh
This PR will add a hashicorp vault instance inside the e2edev test environment. It will be reachable by the e2edev-agbot container.
Changes made :- 
1. `test/Makefile` - Updated targets `run-agbot`, `build` & `clean`. New targets `run-vault`, `hashicorp-vault-image`. Added config variables to run vault server (in dev mode) in a docker container.
2. `test/Dockerfile` - Updated docker cli install script & added vault-cli install script
3. `test/docker/fs/etc/vault/config.json` - Contains vault server configuration details
4. `test/gov/gov-combined.sh` - Add new section to execute vault reachability tests
5. `test/vault_test.sh` - Contains vault http API and cli tests
6. `test/README.md` - Update the lightweight test command
1. https://learn.hashicorp.com/collections/vault/getting-started
2. …
=> Issue 2404 - Add hashicorp vault to e2edev environment

config/config.go, config/config_test.go, test/Makefile, test/docker/fs/etc/agbot/agbot.config.tmpl, test/docker/fs/etc/agbot/agbot2.config.tmpl
Signed-off-by: codejaeger <mandaldebabrata123@gmail.com>
Related to #2451
=> Issue 2451 - Update the agbot config to include vault details

agreementbot/secure_api.go, test/gov/agbot_apitest.sh
Signed-off-by: codejaeger <mandaldebabrata123@gmail.com>
Update the Agbot API with a template to support operations on secrets using the vault API.
Related to issue #2463 
Changes made:- 
1. Add a secret handler function for the agreement bot secure API
2. Add `processVaultUserCred` & `authenticateWithVault` to handle the vault authentication of user/caller.
=> Issue 2463 - Update agbot API to support secrets

externalpolicy/counter_party_properties.go
AgBot would panic when parsing an empty string property because `externalpolicy/counter_party_properties.propertyInArray()` would try to remove quotations when they were not actually there causing an indexing issue in the string slice.
=> Issue 2374 - AgBot panics if node policy has empty property

cli/hzn.go, cli/service/service.go, test/gov/gov-combined.sh, test/gov/service_log_test.sh
Signed-off-by: codejaeger <mandaldebabrata123@gmail.com>
This is a possible fix to #2344. A new (optional) flag `-c` is added to the `hzn service log` cli to take the service container name as input. This helps disambiguate between multiple containers for a service definition.
Updates made:
1. `-c` is an optional flag which needs to be specified if the current service definition has more than one running containers.
2. In a few cases the deployment name of the container is changed to `<service-name>@<repo-digest>`. This PR also accounts for this case.
Note :- There lacks a service in the e2edev tests with multiple containers in its `service.definition.json`. Such a service is needed to make a test to check service logging for individual containers in a deployed service.
=> Issue 2344 - Add -c (container name) flag to hzn service log

agreementbot/secrets/vault/vault.go, cli/cliutils/cliutils.go, cli/hzn.go, cli/secrets_manager/secrets_manager.go, test/gov/agbot_apitest.sh, test/gov/gov-combined.sh, test/gov/hzn_secretsmanager.sh, test/gov/setup_secrets.sh
- Implemented `hzn secretsmanager secret list/add/remove` 
- Changed `test/gov/setup_secrets.sh` to use the CLI instead of the API
- Testing script `test/gov/hzn_secretsmanager.sh`
- Vault plugin returns a 404 instead of a 204 on a DELETE to a secret that doesn't exist 
- Vault plugin filters out the `user/` and empty secret directories when listing org secrets
=> Issue 2479 - 'hzn secretsmanager' commands that talk to the agbot secure APIs to list/add/remove secrets

cli/agreementbot/agreement.go, cli/hzn.go
`hzn agbot agreement list [<agreement>]` is updated to use the given agreement id to filter for requested agreement and list details
=> Issue 2613 - hzn agbot agreement list does not list long details when given agreement id

agreementbot/agreementworker.go, agreementbot/governance.go, agreementbot/secrets/secrets.go, agreementbot/secrets/vault/vault.go, agreementbot/secure_api.go, cli/cliutils/cliutils.go, cli/hzn.go, cli/secrets_manager/secrets_manager.go, exchange/secret.go, test/gov/agbot_apitest.sh, test/gov/hzn_secretsmanager.sh
API changes: `LIST` method supported for listing multiple and individual secrets (for an individual secret, will return `{ exists: true/false }`. `GET` is supported only for individual secrets, and will return the secret details if the user is allowed to read the secret.
=> Issue 2612 - hzn secretsmanager secret read command that allows authenticated users to see secret details

governance/microservice.go, producer/producer_protocol_handler.go
- Add uniqueness to downloaded signing key name to avoid 2 keys overwriting each other
- Change order of validating proposal to rule out proposal for other reasons before checking keys
=> Issue 2596 - Agent fails to verify signature due to internal error

agreementbot/secrets/plugin_errors.go, agreementbot/secrets/vault/vault.go, agreementbot/secure_api.go, cli/secrets_manager/secrets_manager.go, test/gov/hzn_secretsmanager.sh
Created custom errors for the vault plugin in `agreementbot/secrets/plugin_errors.go`. Any errors coming from the vault plugin related to secrets must have the `VaultError` type, which has an `Error()` function as well as functions to retrieve the vault's response and response code.
=> Issue 2651 - Error messages for the 'hzn secretsmanager' commands need to be cleaned up

cutil/cutil.go
This PR is to update the function anax uses to generate tokens. The generated tokens need to match the new exchange standards:
- a digit must occur at least once
- minimum of 15 chars
- one uppercase letter
- one lowercase letter
=> Generated tokens should match exchange standards

abstractprotocol/protocol.go, agreementbot/consumer_protocol_handler.go, events/events.go
_abstractprotocol/protocol.go_ `CreateProposal()` function was updated to log the `Policy` as a pointer instead of a dereferenced pointer because that invoked the `Policy` `String()` method which is cleaner and does not print the secret details.
The `Policy` struct `String()` method is updated to remove newlines so that all the lines are written to the logs.
_producer/producer_protocol_handler.go_ had no instances of the `Proposal` or `Policy` objects being logged with the secret details in its `sendMessage()` function, but since _agreementbot/consumer_protocol_handler.go_ does, I thought it would be nice to put the same fix in both for symmetry and as a preventative measure.
=> Issue 2624 - Check agbot and agent logs for secret details

agreementbot/agreementbot.go
The agbot subworker that keeps it logged into the secrets provider needs to run during init and periodically there after. It was not running during init.
=> Issue 2743 - ensure agbot is logged in to sec mgr during init

agreementbot/agreementbot.go, agreementbot/basic_agreement_worker.go, agreementbot/secret_updater.go, events/secret_events.go
1) Keep track of referenced secrets even if they aren't created yet.
2) Ensure that when the secret is created, agreements are formed as quickly as possible.
3) Got lucky and exposed a problem during testing where an agreement reply AND agreement update reply are processed simultaneously, resulting in one of them having their database update over-written by the other.
=> Issue 2731 - make agreements after secrets are created

agent-install/agent-install.sh
See [issue 2769](https://github.com/open-horizon/anax/issues/2769) for details.
Tested the fix on edge nodes:
- Ubuntu 18
- Ubuntu 20
- RHEL 8.2
=> Issue 2769: agent-install.sh - pre-req check for netstat

agent-install/agent-install.sh, agent-install/agent-uninstall.sh
When the user upgrade edge cluster agent with `./agent-install.sh -D cluster -i 'css:' -s`, which skip the registration, it end up with unregistered. That is because 
1) node name of edge cluster agent node is traced the path of device agent (from horizon env file or hostname). It end up with the node id traced from device agent path is different from current edge cluster deployment. 
2) the cert file is not copied/moved to `/etc/default/cert`, however the cert at that location is checked when we compare old horizon env and new horizon env. 
Then the install script will think current horizon env and current registration is not correct so the script unregisters the agent. 
And because `-s` is specified, it will not registered again.
The PR added …
=> Issue 2850 - agent-install.sh: fix edge cluster upgrade issue

agreementbot/agreementworker.go, agreementbot/policy.go, config/config.go, config/constants.go, exchange/css.go
- Look at each object manager policy individually
- Avoid long log messages printing destinations
- Batch destination updates to CSS to avoid a single huge POST
- Agbot can determine if an agent is already in the destination list to avoid unnecessary call to CSS
=> Issue 2879 - assess each object manager policy

agent-install/agent-install.sh
Add support for Raspberry Pi OS/Debian Bullseye in `agent-install.sh`.
- Added `bullseye` to `SUPPORTED_DEBIAN_VERSION`
- Within `debian_device_install_prereqs()` run a `apt-get update` after adding the Docker repository.
- Virtualbox Version 6.1.32 running Ubuntu 18.04.6 LTS
Installation instructions are followed here:
https://open-horizon.github.io/common-requests/install.html
https://wiki.lfedge.org/display/OH/Sample+Open+Horizon+setup
Tested on:
- Raspberry Pi 4 running Raspberry PI OS Lite (Bullseye) - 64bit
- Raspberry Pi 4 running Raspberry PI OS Lite (Bullseye) - 32bit
- Raspberry Pi 4 running Raspberry PI OS Lite (Buster) - 32bit
On a fresh install of Raspberry PI OS Lite run the following commands:
```
sudo -s -E
apt-get -y update && apt-get -y upgrade && apt-get -y install git …
```
=> Issue-3008: agent-install.sh add support for Raspberry Pi OS arm64 bullseye/debian 11

agreementbot/changes_worker.go, changes/changes_worker.go, cli/register/register.go
This PR fixes https://github.com/open-horizon/anax/issues/3055
`Proceed` in several messages and comments has been corrected.
Signed-off-by: John Walicki <walicki@us.ibm.com>
=> Issue 3055 - Fix proceeed misspelling

Makefile, anax-in-container/README.md
Fix arm64 anax container images by enabling multi-arch builds using Docker Buildx
Fixes #3063 
Internal IBM Jenkins job builds Docker images with and without using Buildx options.
...
=> Issue 3063 - Fix arm64 anax container images

cli/node_management/agentfiles.go, cli/node_management/manifest.go
This PR fixes issue #3091 - Remove version range support from manifest CLI. Before this change, a user could add a Manifest file to the CSS, using the agent CLI, with a manifest file that included version *ranges* for the various upgrade types. However, only version *strings* and "latest" will be the only acceptable ways to specify upgrade versions. With this PR, the `hzn nm manifest add` command will now check the given manifest to make sure the given file versions are version strings or "latest".
This PR also fixes some typos, removes the usage of "version range" from the help outputs.
Finally, this PR also fixes how agent files are sorted when using the `hzn nm agentfiles list` command. Before, versions were sorted in descending order …
=> Issue 3091 - Remove version range support from manifest CLI

cli/node_management/agentfiles.go
This PR fixes the sorting of the files outputted by running `hzn nodemanagement agentfiles list`. Files are now sorted semantically based on their version string rather than lexigraphically.
Fixes #3119
Tested by running `hzn nodemanagement agentfiles list` and checking the output.
=> Issue 3119 - Use semantic versioning for sorting files in hzn nm agentfiles list

cli/dev/utils.go, cli/exchange/user.go, cli/plugin_registry/plugin_registry.go, cli/register/register.go, cli/register/servicewait.go, cli/sdo/key.go, cli/sdo/voucher.go, cli/secrets_manager/secrets_manager.go, cli/unregister/unregister.go, semanticversion/version.go
This PR fixes all known instances of English output being printed to console that was not first translated by running through the i18n message printer.
Fixes #3139
This code is already known to work, so it did not need to be tested. The codebase already runs all hardcoded strings through the message printer, and the changes here do simply that.
=> Issue 3139 - fix missing msgprinter statements for i18n

nodemanagement/node_management_worker.go
Tested reading in sucessful and unsuccessful status files with e2edev agent
...
=> Issue #3151 - Agent removing nmp directory of unsucessful nmps

agent-install/agent-uninstall.sh, agent-install/k8s/auto-upgrade-cronjob-template.yml, agent-install/k8s/persistentClaim-template.yml, anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh
This PR introduces several changes to the edge cluster agent in order for the auto agent rollback cronjob to function properly...
1. The cronjob pod now mounts itself to the same /var/horizon PVC directory as the agent pod so that it can read/write the status.json file directly
- This also meant changing the permissions on the PVC from `ReadWriteOnce` to `ReadWriteMany` so that more than one pod can mount to it
2. The cronjob now looks for the status.json file in the path `/var/horizon/nmp/{org}/{nmp-name}/status.json`
- It will loop through all the directories in the `/var/horizon/nmp/{org}/` path to find the status.json that has the latest `startTime` field. This way it is always working on the last ran auto upgrade job. 
3. The cronjob …
=> Issue 3121 - AgentAutoUpgrade: Fix path to status.json in k8s cronjob script

api/path_management_nextjob.go, api/path_management_nextjob_test.go, cli/exchange/nmp.go, test/gov/apireg.sh, test/gov/gov-combined.sh, test/gov/hzn_nmp.sh
This PR adds tests for the `hzn exchange nmp` set of CLI commands. It also fixes an intermittent timing issue with the go tests on the API module.
Fixes #3166 
This PR is tests, so testing simply involved running the tests and making sure they do not fail or give unexpected output.
=> Issue 3166 - Add NMP CLI tests to e2edev

i18n_translation/hzn.out.gotext.json, i18n_translation/original/hzn.out.gotext.json.auto
=> Issue 3103 - more translation message drop for 2Q2022

download/download_worker.go, exchangecommon/node_management_status.go, nodemanagement/node_management_worker.go, nodemanagement/node_management_worker_test.go
=> Issue #3259 - Bug: NMPs applied in incorrect order

cli/cliutils/cliutils.go, cli/hzn.go
This PR removes the ability to specify the node credential as an exchange credential for admin-only exchange commands.
Right now, this includes the following 2 commands:
- `hzn exchange nmp add`
- `hzn exchange nmp remove`
The error message for omitting a credential was also edited to leave out the node credential as a possible option.
Fixes #3277
This was tested by running the commands listed above and ensuring that the node credential is not accepted. The same commands were also run with the user credential to ensure they work as they did before the change.
A few non-NMP-related exchange commands were also run to make sure they were not affected by this change.
=> Issue 3277 - Remove node credentials as option for admin-only exchange commands

cli/hzn.go, docs/node_management_policy.md, test/gov/hzn_nmp.sh
This PR changes the `--appliesTo` flag for the `hzn ex nmp add` command to `--applies-to` to stay consistent with all other CLI command flags.
The documentation for the NMP CLI commands has also been updated to reflect this change.
Fixes #3294
This was tested by running the command with the new flag and making sure it still runs as expected.
=> Issue 3294 - Change --appliesTo flag to --applies-to on hzn exchange nmp add CLI command

cli/exchange/nmp.go, exchangecommon/node_management_policy.go
This PR adds a check to the NMP validation function to ensure the timestamp given for the start time is actually in RFC3339 format (or "now").
Fixes #3275
This was tested by trying NMP's with the following cases:
- With start omitted (start set to "")
- With start set to "now"
- With start set to various valid RFC3339 timestamps
- With start set to invalid timestamps
=> Issue 3275 - Bug: hzn cli doesn't check for valid RFC3339 format in NMP start time

exchange/css.go
Fixes # #3306
...
- [ x] New and existing unit tests pass locally with …
=> Issue_3306 - Correct retries for download_worker

cli/exchange/nmp.go
This PR adds logic to the `hzn exchange nmp status` CLI command to check that the NMP given as an argument actually exists in the Exchange before polling every node.
Fixes #3312 
This was tested by giving the command an NMP that does not exists in the Exchange, and making sure it returns a fatal error. It was then tested with NMP's that do exist as a regression test to make sure they still get polled across all nodes in the user's scope.
=> Issue 3312 - Bug: NMP isn't checked before checking each nodes status

cli/exchange/nmp.go, exchangecommon/node_management_policy.go
This PR adds a line of code to set the start time of an NMP to "now" when adding the NMP to the exchange if it was set to blank or if it was omitted.
Fixes #3313
This was tested by adding an NMP without the start time defined and making sure it gets set to "now".
=> Issue 3313 - Bug: Creating an NMP doesn't default to start=now like help says

pkg/rpm/horizon/horizon.spec
For the rpm spec file, check for podman first so that we can start the podman service if needed... If podman-docker is installed, we never started the podman service
Fixes # #3305 
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update
Built an RPM package; installed horizon; and made sure podman service was restart
...
- [ x] My changes generate no new …
=> Issue3305 - change podman logic in rpm spec

agreement/agreement.go
=> Issue 3269 - Bug: registeredServices lost in node after upgrade

cli/hzn.go, cli/node_management/manifest.go, cli/sync_service/object.go
This PR adds digital signing to manifest uploads to the CSS. This was a feature already implemented for model uploads, so it was refactored to support manifests as well.
Fixes #3318 
This was tested by uploading a manifest using the `hzn nm man add` command (which now has digital signing), and running a NMP upgrade to make sure it did not break the NMP process. The `hzn mms obj pub` command was also tested to make sure it worked as before.
=> Issue 3318 - Bug: Manifests published by hzn man add CLI command not being digitally signed

cli/exchange/service.go
Typos :
-   overriden should be spelled overridden in cli/exchange/service.go
-  There is an extra space in the string Updating Service policy and re-evaluating in cli/exchange/service.go
Run this command:
```
hzn exchange service addpolicy -f horizon/service.policy.json org/myservice_1.0.0_amd64
Adding built-in property values...
The following property value will be overriden: service.url, service.name, service.org, service.version, service.arch
Updating Service policy  and re-evaluating all agreements based on this Service policy. Existing agreements might be cancelled and re-negotiated.
Service policy updated.
```
Fixes #3360
=> Issue 3360: Fix typos in service.go

.github/workflows/copydocs.yml
Signed-off-by: Joe Pearson <joewxboy@users.noreply.github.com>
CHanged copy docs GHA `dst_owner` to an actual account, and `secrets.PERSONAL_TOKEN` to a personal access token with least privileged permissions.
Fixes #3408 
Read the fine manual when I discovered that the GHA was failing silently, realized we had never done it right and wondered how it ever worked.
FYI ... @johnwalicki and @dabooz
=> Issue-3408: Changed copy docs GHA dst-owner to joewxboy

cli/exchange/ha_group.go
=> Issue #3434 - CLI check ha group description is not empty before attempting to publish it to the exchange

agreementbot/secrets/vault/http.go, cli/cliutils/cliutils.go, config/collaborators.go, config/config.go, config/constants.go, css/horizonAuthenticate.go, exchange/rpc.go
Change for anax (running as agbot) to reuse HTTP connections to the Exchange which will be much more efficient when SSL to the exchange is enabled 
Fixes https://github.com/open-horizon/anax/issues/2698
- [x ] New feature (non-breaking change which adds functionality)
Ran and monitored running as an agent and as agbots
...
- [ x] I have tagged the …
=> Issue2698 - Agbot reuse http conns

changes/changes_worker.go
Change the `POLL_INTERVAL_ALERT_LEVEL` from `2` to `4` 
This will decrease the pollInterval when there is a pending node policy change from 70 seconds to 35 seconds
I also fixed a variety of minor spelling issues in the comments and strings.
Fixes #3473
Run `hzn policy update --input-file=/tmp/changes.json` and watch the logs.
...
=> Issue #3473 - decrease pollInterval on node policy change

anax-in-container/script/anax.service
Revert previous change to go back to using a docker volume for /ess-store when running in anax-in-container
Fixes # https://github.com/open-horizon/anax/issues/3528
Built and run on a samsung phone
...
- [ x] I have tagged the reviewers in a comment below incase my pull request is ready for a …
=> Issue3528 - Use docker volume for /ess-store for anax-in-container

kube_operator/kubeworker.go
Fixes #3554 
Fixes a typo `s/maintenence/maintenance/g`
- [x ] I have checked my code and corrected any misspellings
=> Issue #3554 - fix error msg typo

.github/workflows/build-push.yml
- Added command to purge all old docker and moby dependencies before installing the updated versions for both MacOS and Linux jobs.
Fixes #3841 
- Tested by running the workflow in my fork, checked the outputted docker images to confirm they matched our previously produced images.
...
=> Issue #3841 - Bug: CI Workflow failing due to Docker update step.

test/gov/hzn_dev_services.sh
=> fix e2edev since docker build message is changed with docker buildkit

agreementbot/governance.go, agreementbot/persistence/agreement.go, agreementbot/secret_updater.go, events/secret_events.go
=> Issue 3715 - agbot update node-level pattern secrets

container/container.go
=> open-horizon#3931 - Bug: e2edev failed since move to Docker 24.0.7

container/container.go
Reverts open-horizon/anax#3932. It wasn't fully tested before being merged.
=> Revert "open-horizon#3931 - Bug: e2edev failed since move to Docker 24.0.7"

agent-install/agent-install.sh, agent-install/agent-uninstall.sh, agent-install/k8s/auto-upgrade-cronjob-template.yml, agent-install/k8s/deployment-template.yml, clusterupgrade/cluster_upgrade_worker.go, kube_operator/api_objects.go
=> Issue 3935/3940- enable remote cr

agent-install/agent-install.sh
Attach HZN_NODE_ID at the end of HZN_ENV_FILE so that the file is unique for the installation and >1 agent-install.sh can be run in parallel with different arguments.
Run the agent-install-sh with different parameters, especifically different -d and -k in parallel towards different minikube clusters.
=> Fix aget-install.sh to run in parallel

cli/locales/fr/messages.gotext.json, i18n_translation/anax.out.gotext.json, i18n_translation/hzn.out.gotext.json, i18n_translation/original/anax.out.gotext.json.auto, i18n_translation/original/hzn.out.gotext.json.auto, i18n_translation/translated/anax.out.gotext_fr.json, i18n_translation/translated/hzn.out.gotext_fr.json, locales/fr/messages.gotext.json
=> open-horizon#3896 - Second translation message drop for 3Q2023

agreement/agreement.go
=> Agent cancels agreement after built-in property change

kube_operator/api_objects.go, kube_operator/client.go
Before, secrets were considered and UNSTRUCTURED type, and created last. This is problematic for Deployment resources that may depend on an ImagePullSecret being created first.
Fixes #4081
Tested by installing a service to a k3d cluster running on Ubuntu 20.04 that includes a Deployment YAML and a ImagePullSecret YAML. 
Before the install would fail multiple times due to image pull errors before eventually succeeding. 
Now, the install succeeds on the first try. No image pull errors present anymore.
...
=> Issue 4081 - Make kube worker aware of Secret kube resource type

agent-install/agent-install.sh
below calculation of minor_version of kubectl corrected. This will work for both macosx bash and other linux bash shells
```
minor_version=${minor_version::-1}
```
above code is changed to
```
minor_version=${minor_version::$((${#minor_version} - 1))}
```
Fixes: #4072
Checked by running the agent_install.sh script in macosx bash shell
...
=> fix #4072 : minor_version of kubectl calculated by stripping '+' correctly

MAINTAINERS.md
Fixes #4151 
Move Ling Gao to an Emiterus maintainer.
This matters for LF Edge maintainer surveys in the future.
=> Issue #4151 - update MAINTAINER emeritus list

agreementbot/agreementbot.go, agreementbot/secret_updater.go, config/config.go, config/constants.go
=> Improve the polling of agbot checks the secrets update

agent-install/agent-uninstall.sh
Output log for 'palmctl uninstall openhorizon' command needs better clarity as it's confusing from a user perspective:
Added --ignore-not-found and -f flags to prevent errors related to missing resources.
Fixes #[4181](https://github.com/open-horizon/anax/issues/4181)
=> Improve output log clarity for palmctl uninstall openhorizon

agreement/agreement.go
Trigger mechanism to check if agreement is valid after startup as used when heartbeat is restored
Fixes # https://github.com/open-horizon/anax/issues/4211
Ran test where agreement changed and didn't change when agent was not running and had desired effect
...
=> Keep agent in sync after startup

agreementbot/api.go, api/api.go
Software places user-controlled input in HTTP headers. An attacker could inject line separators (CR/LF sequences) that could split the response message generated by the software into two messages. The second response is completely under the control of the attacker (intermediate web proxies may cache it), with could produce multiple conditions (web defacement, cache poisoning, cross-site scripting or page hijacking, see CWE-113 for full details). If software needs to generate HTTP headers depending on user-controlled input, such input should be properly neutralized (a white-list validation excluding CR/LF is recommended). Please note that cookies are received and sent in 'Cookie' header in HTTP messages, so if the software generates a Cookie from user input, the input should be properly …
=> Fix vulnerabilities CWE-113 (issue #4208 issue #4209)

cli/dev/dependency.go, cli/dev/utils.go, clusterupgrade/cluster_install_files.go, exchange/css.go, imagefetch/image_process_int_test.go, policy/policy_file.go, resource/certificate.go, resource/resource_manager.go
CWE-732: Insecure Directory Permissions
A sensitive sink functions were discovered. It causes a High severity Insecure Directory Permissions vulnerability.
The permission mode  is passed as an integer to the **os.MkdirAll** function, which can lead to unintended permissions. The issue stems from how the permissions are specified in Go. The resulting permissions may be interpreted incorrectly.
**To prevent unintended permissions, you should specify the mode in octal format.**
Fixes #[ (issue)](https://github.com/open-horizon/anax/issues/4222)
Run Mend SAST and check that vulnerabilities were fixed.
=> CWE-732: Insecure Directory Permissions 

anax-in-container/Dockerfile.alpine.amd64, anax-in-container/Dockerfile.ubi.amd64, anax-in-container/Dockerfile.ubi.arm64, anax-in-container/Dockerfile.ubi.ppc64el, anax-in-container/Dockerfile.ubi.s390x, anax-in-container/Dockerfile_agbot.ubi, anax-in-k8s/Dockerfile.ubi.amd64, anax-in-k8s/Dockerfile.ubi.arm64, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.amd64, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.s390x, anax-in-k8s/Dockerfile.ubi.ppc64el, anax-in-k8s/Dockerfile.ubi.s390x, css/image/cloud-sync-service-amd64/Dockerfile.ubi, ess/image/edge-sync-service-amd64/Dockerfile.ubi, ess/image/edge-sync-service-arm64/Dockerfile.ubi, ess/image/edge-sync-service-ppc64el/Dockerfile.ubi, ess/image/edge-sync-service-s390x/Dockerfile.ubi
Use ubi-micro instead of ubi-minimal to reduce the threat surface attack area.
Fixes # ([issue](https://github.com/open-horizon/anax/issues/4227))
Ran make docker for different architectures, like "amd64" ,"ppc64el", "s390x", "arm64" .
```
make ess-docker-image
make auto-upgrade-cronjob-k8s-image
make css-docker-image
make anax-k8s-image
make anax-image
make agbot-image
```
=> Use ubi-micro instead of ubi-minimal to reduce the threat surface attack area.

api/path_publickey.go, cli/dev/utils.go, cli/register/register.go, clusterupgrade/cluster_install_files.go, container/container.go, download/download_worker.go, policy/policy_file.go
CWE-732: Insecure File Permissions refers to a vulnerability where a file or directory has permissions that are too permissive, allowing unauthorized users or processes to read, modify, or execute it. This can lead to a range of security risks, such as unauthorized data access, data corruption, privilege escalation, and even remote code execution in some cases.
Starting from Go 1.16, the **ioutil** package has been deprecated.
Fixes # (#4239 )
- Ran unit-tests
=> Issue #4239 - Fix CWE-732: Insecure File Permissions

api/path_publickey.go, cli/cliconfig/config.go, cli/cliutils/cliutils.go, config/collaborators.go, container/container.go, css/horizonAuthenticate.go
CWE-22 (Path/Directory Traversal) is a type of vulnerability that occurs when an application allows users to manipulate file paths in a way that can access files or directories that are outside of the intended directory. This can lead to security issues such as unauthorized access to sensitive files, data leakage, or even arbitrary code execution in some cases.
Fixes # ([issue](https://github.com/open-horizon/anax/issues/4232))
Canonical Path Resolution: The **filepath.Clean()** method removes redundant or malicious path elements (e.g., .., .) that could be used for directory traversal.
Ran Mend SAST
=> Issue #4232 - Fix CWE-22 Path/Directory Traversal issues

Makefile
=> Issue open-horizon#4290 - Bug: cronjob image has wrong arch

.github/workflows/copydocs.yml, docs/index.md
Updated copydocs.yml to add a second copy command.  The second command copies agent-install.README.md to the docs repo at /docs/anax/docs/overview.md
Further, updated /docs/anax/docs/index.md to point to the new overview.md file.
Fixes #4295 and [docs issue 612](https://github.com/open-horizon/open-horizon.github.io/issues/612)
Need to find a way to test the GitHub Action to confirm that it works.
...
@johnwalicki and @naphelps FYI
=> Issue 4295: Copy over the agent-install README as overview.md

cutil/cutil.go
Description
CWE-22 (Path/Directory Traversal) is a type of vulnerability that occurs when an application allows users to manipulate file paths in a way that can access files or directories that are outside of the intended directory. This can lead to security issues such as unauthorized access to sensitive files, data leakage, or even arbitrary code execution in some cases.
Fixes https://github.com/open-horizon/anax/issues/4232
Canonical Path Resolution: The filepath.Clean() method removes redundant or malicious path elements (e.g., .., .) that could be used for directory traversal.
=> Issue open-horizon#4232 - Fix CWE-22 Path/Directory Traversal issues

.github/workflows/copyagentreadme.yml
GitHub Action which will copy the agent-install/README.md to the Docs repo
First step toward fixing  #  4300
...
=> Issue #4300 - Copy agent-install README to Docs repo

agent-install/agent-uninstall.sh
When following the official gw deletion scenario, the gateway deletion automatically remove the node, causing an error output:
```
[ERROR] Error: node 'node-name' not found in org 'org-name'
[ERROR] command terminated with exit code 8
```
This message was confusing, as it implied the node "was not removed." With this change, exit code 8 is now interpreted as a successful outcome, indicating that the node was already removed.
=> Fix palmctl uninstall command output 

anax-in-container/Dockerfile.alpine.amd64, anax-in-container/Dockerfile.ubi.amd64, anax-in-container/Dockerfile.ubi.arm64, anax-in-container/Dockerfile.ubi.ppc64el, anax-in-container/Dockerfile.ubi.s390x, anax-in-container/Dockerfile_agbot.ubi, anax-in-k8s/Dockerfile.ubi.amd64, anax-in-k8s/Dockerfile.ubi.arm64, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.amd64, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el, anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.s390x, anax-in-k8s/Dockerfile.ubi.ppc64el, anax-in-k8s/Dockerfile.ubi.s390x, css/image/cloud-sync-service-amd64/Dockerfile.ubi, ess/image/edge-sync-service-amd64/Dockerfile.ubi, ess/image/edge-sync-service-arm64/Dockerfile.ubi, ess/image/edge-sync-service-ppc64el/Dockerfile.ubi, ess/image/edge-sync-service-s390x/Dockerfile.ubi
libxml2 before 2.12.10 and 2.13.x before 2.13.6 has a use-after-free in xmlSchemaIDCFillNodeTables and xmlSchemaBubbleIDCNodeTables in xmlschemas.c. To exploit this, a crafted XML document must be validated against an XML schema with certain identity constraints, or a crafted XML schema must be used.
[4319](https://github.com/open-horizon/anax/issues/4319)
=> Update libxml2 version

pkg/deb/Makefile
This PR updates Debian packaging step so that both the control and data archives inside the .deb use XZ compression instead of the default Zstd. This resolves installation failures on systems where Zstd-compressed archives aren’t handled by dpkg.
[4340](https://github.com/open-horizon/anax/issues/4340)
=> Issue open-horizon#4340 - Use-xz-instead-of-zstd-for-deb

cutil/cutil.go
=> Issue open-horizon#4410 - Agent failed to parse exchange timestamp
