open-horizon/anax

- agreementbot/agreementbot.go
- ethblockchain/blockchainworker.go
- events/events.go
- governance/governance.go
- main.go
Moved funding delay to a new worker that issues an event when funding is complete.
> no longer block for funding

- api/api.go
- cutil/cutil.go
Always advertise value of GOARCH as value of arch property
> arch from GOARCH

- agreement/agreement.go
- exchange/rpc.go
- governance/governance.go
- persistence/persistence.go
1. Added termination reason to terminated DB records
2. Correctly propagated device name through to device PUT in exchange
> saved cancel reason

- agreement/agreement.go
- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/governance.go
- agreementbot/persistence.go
- citizenscientist/protocol.go
- exchange/rpc.go
- governance/governance.go
- persistence/persistence.go
1. Added whisper message sent from agbot to device indicating receipt of data at the ingest. Anax saves the time in its database with the agreement.
2. Fixed an issue where anax delays starting containers until after it is funded.
> US 438 and some fixes

- agreement/agreement.go
- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
This reverts commit a6e1893f307648f4b7e21e2e24ede035e5a5f052, reversing
changes made to 6f591c132d7798c52da800a6d14ba47e416e6d53.
> Revert Merge pull request #76 from michaeldye/feature/robust_path_building

- agreement/agreement.go
- citizenscientist/protocol.go
- ethblockchain/funding.go
- ethblockchain/identity.go
- persistence/persistence.go
- vendor/vendor.json
And some other minor adjustments
> fixes to upgrade to eth 1.5.5

- container/container.go
- governance/commands.go
various fixes to support shared workload containers
> issue173 fix

- agreement/agreement.go
- agreementbot/activecontracts.go
- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/governance.go
- citizenscientist/protocol.go
- config/constants.go
- ethblockchain/blockchainworker.go
- ethblockchain/rpc.go
- exchange/message_worker.go
- exchange/rpc.go
- governance/governance.go
See issue 169 for description of changes.
> handle http client timeouts

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/api.go
- agreementbot/commands.go
- agreementbot/persistence.go
- agreementbot/wl_persistence.go
- citizenscientist/protocol.go
- doc/agreement_bot_api.md
- events/events.go
See issue 206 for changes in this PR.
> upgrade API to force a device to attempt upgrade

- api/api.go
- api/status.go
> adjusted status output to report connectivity and configuration data without blockchains

- config/config.go
- config/config_test.go
Dedicated to @bmpotter and @linggao.
> move exchange URL to envvar from config file

- api/api.go
- api/path_attributes.go
Ensure that policy attributes make it into the node side policy files.
> properly handle policy attributes in the API

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- api/api.go
- api/path_attributes.go
- events/events.go
- policy/ha_group.go
- policy/ha_group_test.go
- policy/policy_file.go
- policy/policy_file_test.go
Follow-on updates to the pattern support which enables blockchain and HA features to work again.
> Issue345 - complete HA with pattern support

- api/api.go
- api/connectivity.go
- config/config.go
- container/container.go
- cutil/cutil.go
- events/events.go
- governance/commands.go
- governance/governance.go
- governance/status.go
- governance/status_test.go
> issue 313 - Anax update exchange with container status

- api/api_publickey.go
- api/common_test.go
- api/path_publickey.go
- api/path_publickey_test.go
- api/path_workload_config_test.go
- api/path_workload_test.go
- worker/worker.go
- worker/worker_test.go
Just a couple of days of work, more to come in future PRs.
> Issue 453 - Increase API unit test coverage

- cli/agreement/agreement.go
- cli/attribute/attribute.go
- cli/cliutils/cliutils.go
- cli/exchange/node.go
- cli/exchange/pattern.go
- cli/exchange/user.go
- cli/hzn.go
- cli/key/key.go
- cli/metering/metering.go
- cli/node/node.go
- cli/register/register.go
- cli/service/service.go
- cli/workload/workload.go
To allow the to view patterns before registration, i also needed to give them a way to create the node id/token before registration.
> added viewing patterns to hzn

- Makefile
- agreementbot/agreementworker.go
- cli/dev/deploymentconfig.go
- cli/dev/microservice.go
- cli/dev/userinput.go
- cli/dev/utils.go
- cli/dev/utils_test.go
- cli/dev/workload.go
- cli/hzn.go
- cli/register/register.go
- container/container.go
- cutil/cutil.go
- exchange/rpc.go
- governance/governance.go
- persistence/workload_config.go
The next phase of support. Still not completely done.
> Issue 419 - Start and stop workloads in test mode

- api/api_int_test.go
- api/path_publickey.go
- api/path_workload_test.go
- vendor/vendor.json
> added support for x509 cert upload to Anax API, basic test to verify it

- cli/exchange/microservice.go
- cli/exchange/pattern.go
- exchange/rpc.go
- exchange/rpc_test.go
- governance/workload_test.go
Added more transport error checkings for calling to the exchange
Reformatted some files from cli
Moved the workload_test from persistence to governance
> Added more transport error checkings for calling to the exchange

- cli/agreement/agreement.go
- cli/cliutils/cliutils.go
- cli/exchange/agbot.go
- cli/exchange/microservice.go
- cli/exchange/node.go
- cli/exchange/pattern.go
- cli/exchange/user.go
- cli/exchange/workload.go
- cli/hzn.go
- cli/node/node.go
- cli/register/register.go
- cli/service/service.go
* get real version from anax via 'hzn version'
* added list of 1 agreement detail
* removed need for USING_API_KEY
* added `hzn microservice registered`
* added --dry-run flag
> More hzn function

- cli/cliutils/cliutils.go
- cli/exchange/microservice.go
- cli/exchange/pattern.go
- cli/exchange/service.go
- cli/exchange/workload.go
- cli/hzn.go
- exchange/rpc.go
- version/version.go
- beta of service resource
- adding signing public keys as sub-resource to microservice, workload, pattern, service
> added support for exch service resource and for adding pub keys to exch

- api/path_microservice_config.go
- api/path_node_configstate.go
- cli/exchange/microservice.go
- cli/exchange/service.go
- cli/exchange/workload.go
And also formatted a few cli files.
> Fixed an issue that checking workload config in wrong place.

- Makefile
- cli/exchange/node.go
- cli/exchange/user.go
- cli/hzn.go
- cli/register/register.go
Added:
- `hzn exchange user create ...`
- `hzn exchange user setadmin ...`
- `hzn exchange node settoken ...`
- `hzn exchange node confirm ...`
> Hzn admin cmds

- test/README.md
Changed the anax URL for cloning in README.md file.
> fixed the anax git url in the instruction

- container/container.go
Please review the comment of issue 687 for design details.
> Issue 687 - Use docker volumes for service persistence

- cli/exchange/pattern.go
- cli/exchange/service.go
- cli/hzn.go
Fixes issue https://github.com/open-horizon/anax/issues/742
> fix viewing other orgs

- Makefile
- css/horizonAuthenticate.go
- events/events.go
- persistence/attribute_types.go
- test/Makefile
- torrent/torrent_int_test.go
Enable the CSS authentication plugin to use exchange SSL endpoint.
> Support exchange SSL for CSS authentication plug in

- cli/native_deployment/native_deployment.go
- container/container.go
- containermessage/models.go
> Issue 903 - Add Tmpfs Support

- doc/deployment_string.md
Update deployment_string.md with Tmpfs information.
> Issue 903 - Tmpfs Documentation Update

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/basic_protocol_handler.go
- agreementbot/businesspol_manager.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/nodehealth_manager_test.go
- agreementbot/persistence/agreement.go
- agreementbot/persistence/bolt/agreement.go
- agreementbot/persistence/database.go
- agreementbot/persistence/postgresql/agreement.go
- test/gov/service_apireg.sh
This pass just cancels the agreement whenever that is a change in the related service policy.
> Agbot handle service policy changes

- cli/exchange/business.go
- cli/hzn.go
- events/events.go
- imagefetch/image_process_int_test.go
- persistence/attribute_types.go
Note: running "anax/make format" caused some unrelated formatting changes to be included
> Issue #981 - Short list for 'hzn exchange business listpolicy'

- cli/cliconfig/config.go
- cli/hzn.go
override = false for all setenvvars
> issue #1014 - Env variables override config files

- anax-in-container/horizon-container
- anax-in-container/service/anax.service
- api/path_node_userinput.go
- cli/cliutils/cliutils.go
Unrelated changes in `api/path_node_userinput.go` are from `make format`
> Issue #1072 - Add certificate argument to /etc/default/horizon

- governance/messages.go
> issue 1112 - fixed datavase typo

- agreementbot/api.go
- main.go
curl localhost:8082/config | jq
> Issue 1156 - New Agbot API to display config file information

- agent-install/README.md
- agent-install/agent-install.sh
Initial version of the agent-install script and readme
> initial version of the agent-install script

- agent-install/README.md
- agent-install/agent-install.sh
+ added node policy support;
+ added autocomplete setup;
+ added configurable output;
+ small bug fixes and updates;
> Agent install updates:

- agent-install/README.md
- agent-install/agent-install.sh
+ added node policy support;
+ added autocomplete setup;
+ added configurable output;
+ small bug fixes and updates;
> Agent install updates

- agent-install/agent-install.sh
- a fix for autocomplete issue #1340
- removed a double negative in the message
> Small improvements for the agent install script (master)

- agent-install/agent-install.sh
- a fix for autocomplete issue #1340
- removed a double negative in the message
> Small improvements for the agent install script

- agent-install/agent-install.sh
> Issue #1331 - don't match substrings when checking busy ports in agent-install

- externalpolicy/constraint_expression_test.go
- externalpolicy/counter_party_properties.go
Added a unit test case for this
> Issue #1325 - Multi-value policy properties not selected correctly

- agent-install/agent-install.sh
Will not overwrite configured node unless -f specified
Will not install older or equal version unless -f specified
Expecting zip file **agent-install-files.tar.gz** containing: 
**agent-install.cfg**
**agent-install.crt** 
**node-id-mapping.csv**
**\<OS\>/\<DISTRO\>/\<CODENAME\>/\<ARCH\>/.debs**
> Issue #1305 - support batch node install

- agreementbot/secure_api.go
If SecureAPIServerCert or SecureAPIServerKey is empty in the agbot configuration file, then the secure api will be brought up without TLS. The API calls will accept HTTP instead of HTTPS.
> Bring up non TLS API when cert and key are not set for agbot

- agreementbot/secure_api.go
- doc/agbot_secure_api.json
- doc/agreement_bot_api.md
- test/gov/agbot_apitest.sh
Also changed the the following APIs path
````
/policycompatible
/userinputcompatible
/deploycompatible
````
to 
````
/deploycheck/policycompatible
/deploycheck/userinputcompatible
/deploycheck/deploycompatible
````
> Issue 1443 - Create OAI JSON file for agbot secure APIs.

- agent-install/agent-install.sh
Set node id with flag -d or in the agent-install.cfg file as NODE_ID
Give a clear error message if the exchange cannot be reached with the given information
Allow certificate to be specified with a relative or absolute address
> Allow the agent-install node id to be set with a parameter

- agent-install/agent-install.sh
- Fixed some syntax issues
- Ensure pattern and policy are preserved when not overwriting an existing node
> Make default batch install behavior to install on a registered node.

- agent-install/agent-install.sh
- Accept absolute or relative certificate paths
- Don't use 'echo -e' on mac due to inconsistent behavior with different versions of echo
> Only use the newest horizon package on macOs agent install

- agent-install/agent-install.sh
Fixed a bug causing node to register with hostname instead of given node id in some cases
> Update the supported os's versions and architectures in agent install

- Makefile
agent k8s image use the same tag as agent
> Issue 1627 - Part1: Automate Agent Install in Edge Cluster in Script

- cli/cliutils/cliutils.go
- cli/hzn.go
- cli/sdo/voucher.go
- go.mod
- test/Makefile
- test/README.md
- test/gov/gov-combined.sh
- test/gov/hzn_voucher.sh
- test/gov/run_kube.sh
Issue 1615:
- hzn voucher inspect
- hzn voucher import
- e2edev tests
> Issue 1615 - 'hzn voucher import' sub-command for SDO

- agent-install/agent-install.sh
- fixed error code checking issue 
- removed `validate_exchange` function 
- removed `set_pattern_from_exchange` function
- removed `set_policy_from_exchange` function
- save node id to `/etc/default/horizon`
> fixed node check error and error code checks

- abstractprotocol/protocol.go
- api/path_service_config.go
- basicprotocol/protocol.go
- cli/dev/utils.go
- cli/policy/policy.go
- cutil/cutil.go
- exchangesync/node_policy.go
- externalpolicy/builtin_properties.go
- governance/governance.go
- kube_operator/client.go
- microservice/microservice.go
- persistence/attributes.go
- persistence/persistence_int_test.go
- producer/producer_protocol_handler.go
The new function GetClusterCountInfo is in cutil as a work-around for a package import cycle
> Issue 1593 - Add built-in node policy for cluster agent

- agent-install/agent-uninstall.sh
Enhancement - add 'skip unregister' to uninstall script
> Enhancement - add 'skip unregister' to uninstall script

- agent-install/agent-install.sh
- agent-install/agent-uninstall.sh
- agent-install/k8s/deployment-template.yml
- agent-install/k8s/persistentClaim-template.yml
agent install/uninstall script
> Enhancement - allow user to pass in namespace from cfg file for

- agent-install/agent-install.sh
Fox for bug https://github.com/open-horizon/anax/issues/1780
> added docker check to linux install

- governance/governance.go
- governance/status.go
- persistence/node_status.go
Found that the node status was not being updated in the operator case. Created a subworker to periodically check if the status has changed and save to the local db and update the exchange copy if it has.
> Issue 1789 - Edge cluster node status shows services in Terminating state when they are running

- agent-install/agent-install.sh
With this change:
- User need to set `IMAGE_ON_EDGE_CLUSTER_REGISTRY` (without tag) before running agent install
- `AGENT_IMAGE_TAG` will be read from `agent-install.cfg`
- `IMAGE_FULL_PATH_ON_EDGE_CLUSTER_REGISTRY` is consist of `IMAGE_ON_EDGE_CLUSTER_REGISTRY` and `AGENT_IMAGE_TAG`
- For microk8s and minikube, user don't have to set username and token for edge cluster registry
Also change the way handle image name in deployment for different cases:
- if user pass in `-U <internal-registry-url>` or set `INTERNAL_URL_FOR_EDGE_CLUSTER_REGISTRY` as env, this value will always be used in deployment.yml
- else, will check if kube cluster is runnning locally:
- if running locally, will use `IMAGE_FULL_PATH_ON_EDGE_CLUSTER_REGISTRY` in deployment.yml
- if not running locally (ocp), will use …
> handle image name in deployment.yml for ocp registry

- agent-install/agent-install.sh
- Reduced how verbose it was in printing the input values. Can still see all info with `-l 5`
- For insecure registry like microk8s, when `EDGE_CLUSTER_REGISTRY_USERNAME` and `EDGE_CLUSTER_REGISTRY_TOKEN` are not specified, do not run `docker login ...` so it doesn't prompt for username
> reduce agent-install.sh vebosity of input values

- agent-install/agent-install.sh
@t-fine could you review # 1 and # 2? 
1. Check deploy type with exchange node type:
- For cluster type: checked if the node is already been created with type "device"
- For device type: checked if the node is already been created with type "cluster"
Give back error message for ^^ cases
2. for mac os, if NODE_ID is empty, using hostname as node id
3. Remove create node for cluster type in function "create_node()"
4. For cluster type, if agent is already registered with different node id, give error message
5. For cluster type, if agent is already registered with same node id, skip registration
6. add support for `k3s kubectl`
> Issue 1848 - Agent-Install Idempotency Issue - function registration()

- cli/hzn.go
- cli/register/register.go
- cli/register/servicewait.go
This fixes issue 1422 and 1423.
> Issue 1422 - hzn register waits for all services in a pattern

- cli/cliutils/cliutils.go
- cli/exchange/agbot.go
- cli/exchange/business.go
- cli/exchange/node.go
- cli/exchange/org.go
- cli/exchange/pattern.go
- cli/exchange/service.go
- cli/exchange/user.go
- cli/hzn.go
- cli/register/register.go
- cli/sdo/voucher.go
- cli/sync_service/object.go
Signed-off-by: lichristina118 <lichristina118@gmail.com>
> Issue 1905 - CLI get a list of nodes that a service is running on

- test/gov/hzn_voucher.sh
Signed-off-by: Troy Fine <Troy.Fine@ibm.com>
> tests for hzn voucher list

- cli/cliutils/cliutils.go
> Issue 1674 - Status indicator for MMS publish command

- agent-install/agent-install.sh
- agent-install/edgeNodeFiles.sh
- removed the installation of the bluehorizon pkg
- update for new pkg file names that don't include distro or codename
> Issue #1694 - remove the installation of the bluehorizon pkg, and update for new pkg names

- cli/cliutils/cliutils.go
> Issue 1992 - Status indicator for MMS download command

- test/gov/api_key.sh
- test/gov/hzn_dev_services.sh
- test/gov/msghub_rsrcreg.sh
- test/gov/service_apireg.sh
> Fixed a service key verification problem for remote e2edev

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Third PII drop for fall 2020

- cli/register/register.go
> Issue 1952 - new format of 'hzn reginput'

- test/Makefile
- test/gov/init_exchange.sh
> Issue 2018 - Remote e2edev failed because the service cache is old

- agent-install/agent-install.sh
- agent-install/agent-uninstall.sh
> Issue 1694: overhaul of agent-install.sh

- docs/built_in_policy.md
> Issue 1929 - Document Policy Properties

- cli/dev/utils.go
- cli/native_deployment/native_deployment.go
> Issue 989 - Path permissions misaligned

- cli/dev/dependency.go
- cli/dev/userinput.go
- cli/dev/utils.go
- common/exchange_input.go
- common/userinput_file.go
- policy/user_input.go
> Issue 1997 - 'hzn dev' use new userinput format

- agent-install/agent-install.sh
> Issue 1886: added rhel/rpm support to agent-install.sh

- agreementbot/changes_worker.go
- cache/cache.go
- cache/simple_map_cache.go
- exchange/cache.go
- exchange/cache_test.go
- exchange/changes.go
> Issue #2016 - anax should invalidate the cache when an org is removed

- cli/service/service.go
- pkg/rpm/README.md
Signed-off-by: Liang Wang <losdevnull@gmail.com>
issue #1967
> Issue 1967 - Determine system log file path based on linux distribution

- exchange/pattern.go
- exchange/policy.go
> Issue 1849 - Intermittent OOM with 1000's of business policies

- agent-install/agent-install.sh
> Issue: 1694: fixed problem when cfg file not used

- .travis.yml
> Issue 2044 - parallelize Travis CI tests

- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/hzn.out.gotext.json.auto
> Forth PII drop for fall 2020

- test/gov/pattern_change.sh
> Added more waiting time for the e2edev pattern change test.

- agreementbot/pattern_manager_test.go
- api/common_test.go
- api/path_node_configstate_test.go
- api/path_service_config_test.go
- cli/dev/utils_int_test.go
- css/horizonAuthenticate.go
> Issue 2004 - Unit test failures in governance, api , and agreement bot

- cli/dev/servicedefinition.go
> Issue 2035 - 'hzn dev service verify' failed to verify netspeed service

- agreement/agreement.go
- governance/governance.go
- test/Makefile
- version/version.go
> Issue 1995 - use exchange /msgs/id API to verify msg existence

- agent-install/agent-install.sh
> Issue 1694: add download support from anax release and CSS

- agreementbot/agreementworker.go
- agreementbot/basic_agreement_worker.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/node_search.go
- agreementbot/persistence/postgresql/workload_usage.go
- agreementbot/prioritized_workqueue.go
- businesspolicy/business_policy.go
- exchange/pattern.go
- policy/policy_file.go
- policy/workload.go
> Issue 1875 - Agbot remove glog.V(3) calls that produce a long string

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/anax.out.gotext_fr.json
- i18n_translation/translated/anax.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
- locales/fr/messages.gotext.json
- locales/ja/messages.gotext.json
> Added translated files for 4th drop of 3Q 2020

- cli/agreementbot/getcache.go
- cli/register/register.go
> Not use message printer when there is no translation needed.

- api/input_validation.go
- api/input_validation_test.go
- cli/cliutils/cliutils.go
- exchange/rpc.go
> Issue 1996 - Unicode Support inconsistent among different commands

- exchange/cache.go
- exchange/rpc.go
- exchange/service.go
> Issue #1840 - agbot sometimes not using cached exchange version

- cli/exchange/node.go
Issue 2026 - Display or log warning when node reach 5% org maxNodes Limits in CLI
Signed-off-by: Igor Kolinko <ikolin@softserveinc.com>
> Issue 2026 - Display or log warning when node reach 5% org maxNodes Limits in CLI

- cli/locales/fr/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_fr.json
> Updates for some translated messages

- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/hzn.out.gotext.json.auto
> Fifth PII drop for fall 2020

- docs/built_in_policy.md
- docs/policy.md
- docs/properties_and_constraints.md
> Issue 882 - some initial policy doc

- Makefile
- agent-install/agent-install.sh
- agent-install/edgeNodeFiles.sh
- pkg/deb/Makefile
- pkg/deb/horizon-cli/DEBIAN/postinst
- pkg/deb/horizon-cli/DEBIAN/postrm
- pkg/mac/Makefile
- pkg/rpm/horizon-cli/Makefile
- version/version.go
And updated anax build to dynamically set version, and include our scripts in horizon-cli
> Issue 2067: added CSS support to edgeNodeFiles.sh and agent-install.sh

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
> Translated text for the fifth PII drop

- cli/locales/it/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_it.json
> More translated messages

- test/gov/verify_surfaced_error.sh
> Fixed surface error testing problem in e2edev

- pkg/rpm/horizon-cli/Makefile
> Issue 2067: fixed error in horizon-cli RPM build

- agent-install/agent-install.sh
- agent-install/edgeNodeFiles.sh
> Issue 2067: fix agent-install.sh for new rpm pkg

- cli/exchange/org.go
- cli/hzn.go
> Issue 2081 - 'hzn exchange org delete' agbot cleaning

- agent-install/agent-install.sh
- pkg/rpm/horizon-cli/.gitignore
> Issue 2067: fixed -e problem in agent-install.sh

- agent-install/agent-install.sh
> Issue 2067: fixed agent-install.sh not installing horizon-cli on macos

- agreementbot/businesspol_manager.go
- agreementbot/node_search.go
- config/config.go
- config/constants.go
> Issue 2094 - search most recently updated policies first

- exchange/messaging.go
> Issue #2116 Agbot sometimes using wrong messaging key for cluster nodes

- agreementbot/basic_protocol_handler.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/node_search.go
- config/config.go
- config/constants.go
- worker/worker.go
> Issue 2120 - fully process changed policies

- Makefile
- agent-install/agent-install.sh
- agent-install/edgeNodeFiles.sh
> Issue 2067: unregister before changing settings

- pkg/deb/Makefile
> Fixed a problem that horizon-cli deb package created wrong file

- pkg/deb/Makefile
> Fixed a typo for deb packaging

- agent-install/agent-install.sh
> Issue 2067: handle when older pkgs already in dir

- anax-in-container/config/agbot.json.tmpl
> Issue 2134 - update agbot config to support large and small scale

- common/userinput_file.go
- governance/status.go
- policy/user_input.go
> Issue 2131 - Anax reports wrong status after the agreement is canceled

- pkg/deb/horizon/DEBIAN/postinst
> Issue #2123 - Agent failed to restart after systemd crash

- cli/eventlog/eventlog.go
> Issue 2147 - hzn eventlog list displays unicode.

- agent-install/agent-install.sh
Signed-off-by: zhangl  <zhangl@us.ibm.com>
> Issue #2149 - Agent install update

- exchange/policy.go
> Issue #2157 - Agbot not using cached node policies

- agent-install/agent-install.sh
> Issue 2159: agent-install.sh check for existence of amd64_anax_k8s.tar.gz

- cli/eventlog/eventlog.go
> 'hzn eventlog list' prints ] at the end of many of the output lines

- agent-install/agent-install.sh
> Issue 2166: fix agent-install.sh to work with virgin sdo css case

- agent-install/edgeNodeFiles.sh
> fixed clean cmd in edgeNodeFiles.sh

- cli/cliutils/cliutils.go
Signed-off-by: Anukriti Jain <anukriti251298@gmail.com>
> Issue 1908 - Added req.Close=true as a potential fix

- cli/cliutils/cliutils.go
Signed-off-by: Igor Kolinko <ikolin@softserveinc.com>
> Issue 1611 - hzn gives incorrect advice on macos

- cli/hzn.go
- cli/sync_service/object.go
> Issue 2175 - Argument inconsistency in `hzn mms ...`

- cli/cliutils/stdout_logging.go
- cli/dev/service.go
- cli/dev/utils.go
- cli/hzn.go
- cli/service/service.go
- container/container.go
> Issue 1498 - support hzn service log when using hzn dev

- api/path_node.go
- cli/unregister/unregister.go
> Issue 2155 - 'hzn unregister -fD' when in unconfiguring state

- cli/register/register.go
> Issue 2169 - Node registration with special unicode character

- cli/native_deployment/native_deployment.go
- container/container.go
- containermessage/models.go
- docs/deployment_string.md
> Issue 1195 - Horizon "deployment string" support the entrypoint override

- cli/register/servicewait.go
> Issue 1424 - hzn register incremental progress

- cli/native_deployment/native_deployment.go
- container/container.go
- containermessage/models.go
- docs/deployment_string.md
- test/gov/hzn_dev_services.sh
> Issue 1419 - configurable memory and CPU limits for a service

- container/container.go
> Issue 1892 - docker network bridge not needed for "network:host"

- Makefile
Signed-off-by: bencourliss <bencourliss@ibm.com>
> Updated Anax, CSS, and ESS version numbers for next release

- test/README.md
- test/gov/gov-combined.sh
- test/gov/service_upgrading_downgrading_test.sh
> Issue 715 - Add service upgrading and downgrading tests

- cli/exchange/version.go
- cli/hzn.go
> Issue 794 - hzn cli should prevent version mismatches with the Exchange

- cli/hzn.go
> Issue 2198 - 'hzn exchange org create' command asks for HZN_ORG_ID

- cli/cliutils/cliutils.go
- cli/native_deployment/native_deployment.go
- cli/service/service.go
- container/container.go
- containermessage/models.go
- docs/deployment_string.md
> Issue 2097 - Anax breaks docker logging

- cli/cliutils/cliutils.go
- cli/dev/service.go
- cli/service/service.go
> Issue 2199 - Service logs for services with alternative drivers

- agreementbot/api.go
- apicommon/status.go
- exchange/cache.go
> Issue #2196 - Break agbot dependency on Exchange for its health check

- test/gov/check_node_status.sh
- test/gov/hzn_reg.sh
- test/gov/pattern_change.sh
- test/gov/verify_agreements.sh
> Issue 1399 - exchange node status testcase

- test/gov/verify_agreements.sh
Signed-off-by: Nadim Jabbour <Nadim.Jabbour@ibm.com>
> Increase Remote Timeout

- docs/agreement_bot_api.md
- docs/api.md
> Remove use of bluehorizon.network

- events/events.go
- governance/governance.go
- governance/messages.go
- imagefetch/image_process.go
> Issue 2227 - Surface docker image fetch errors from the agent

- Makefile
- anax-in-container/Dockerfile.ubi.s390x
- anax-in-container/README.md
- pkg/rpm/README.md
- tools/arch-tag
> Issue 2182 - Anax s390x support feature

- Makefile
- css/horizonAuthenticate.go
- go.mod
> Increase Sync Servicer version to 1.5.1

- README.md
- anax-in-container/README.md
- pkg/rpm/README.md
> Issue 2245 - Anax cross-platform build notes

- pkg/rpm/horizon/horizon.spec
> Issue 2190: remove curly braces from rpm horizon.spec

- Makefile
- README.md
- agent-install/README.md
- anax-in-container/Dockerfile.amd64
- anax-in-container/Dockerfile_agbot.amd64
- anax-in-container/README.md
Fix the issue #2205 , @bmpotter , Could you help review this, Thanks
> Remove use of bluehorizon deb pkg

- agent-install/agent-install.sh
> Issue 2259: fixed problems listed in issue 2259

- pkg/mac/scripts/horizon-cli-uninstall.sh
> Issue 2150: have horizon-cli-uninstall.sh also stop agent container

- pkg/rpm/horizon-cli/Makefile
- pkg/rpm/horizon/Makefile
> Issue 2254 - Failed to build RPMs - gzip: unrecognized option '--keep'

- agent-install/agent-install.sh
By setting any of the following environment variables, you can get `agent-install.sh` to allow those additional platform types: SUPPORTED_OS_APPEND, SUPPORTED_LINUX_DISTRO_APPEND, SUPPORTED_DEBIAN_VARIANTS_APPEND, SUPPORTED_DEBIAN_VERSION_APPEND, SUPPORTED_DEBIAN_ARCH_APPEND, SUPPORTED_REDHAT_VARIANTS_APPEND, SUPPORTED_REDHAT_VERSION_APPEND, SUPPORTED_REDHAT_ARCH_APPEND.
Comments at the beginning of the script provide more details about the keywords that should be used for each.
> Issue: 2215: add ability to pass into agent-install.sh additional distros, versions, arches that it should allow

- test/gov/check_node_status.sh
- test/gov/gov-combined.sh
> Fixed node status checking for e2edev

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> First PII drop for translation for 1Q2021

- agent-install/agent-install.sh
> Issue 2040 (part2) - Agent-install.sh edge cluster fixes/improvements

- resource/resource_manager.go
> Issue 2275 - Create ESS API socket listener path if it does not exist

- agent-install/agent-install.sh
> Issue 2040 (part3) - Agent-install.sh edge cluster fixes/improvements

- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/hzn.out.gotext.json.auto
> Second PII drop for translation for 1Q2021

- Makefile
- basicprotocol/diagrams/horizonSequenceDiagram.txt
- basicprotocol/diagrams/protocolSequenceDiagram.txt
- cli/dev/service.go
- cli/dev/utils.go
- cli/native_deployment/native_deployment.go
- cli/sync_service/sync_service.go
- common/deploymentconfig.go
- container/commands.go
- container/container.go
- containermessage/models.go
- cutil/cutil.go
- events/events.go
- governance/governance.go
- governance/microservice.go
- microservice/microservice.go
- test/docker/fs/hzn/service/leaf/Dockerfile
- test/docker/fs/hzn/service/leaf/Makefile
- test/docker/fs/hzn/service/leaf/service.sh
- test/docker/fs/hzn/service/leaf/start.sh
- test/gov/gov-combined.sh
- test/gov/hzn_dev_services.sh
- test/gov/hzn_reg.sh
- test/gov/service_configstate_test.sh
- test/gov/service_retry_test.sh
- test/gov/service_upgrading_downgrading_test.sh
- test/gov/verify_agreements.sh
- test/gov/verify_surfaced_error.sh
> Issue 2095 - Bidirectional communication with dependencies

- Makefile
- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
> Added support for building ESS on ppc64el

- Makefile
> Fixed issue with Makefile

- agent-install/agent-install.sh
- agent-install/edgeNodeFiles.sh
> Issue 2243 - Add Power (ppc64le) support to agent-install.sh

- cli/dev/utils.go
- cli/dev/utils_int_test.go
- container/container.go
- semanticversion/version.go
- semanticversion/version_test.go
> Issue 2309 - index out of range in semantic version library

- docs/deployment_policy.md
- docs/model_policy.md
- docs/policy.md
> Issue 882 - document JSON objects

- cli/dev/utils.go
- container/container.go
- imagefetch/imagepull.go
> Issue 2316 - Image pull does not use the auth for docker.io repo

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
> Translated messages for the second PII drop of 1Q2021

- governance/microservice.go
- test/gov/service_configstate_test.sh
- test/gov/service_upgrading_downgrading_test.sh
- test/gov/verify_agreements.sh
- test/gov/verify_surfaced_error.sh
> Issue 2291 - Agreementless services terminate unexpectedly

- Makefile
- container/container.go
- cutil/cutil.go
- ess/image/edge-sync-service-amd64/Dockerfile.ubi
- go.mod
- resource/authentication_manager.go
- resource/certificate.go
- test/docker/fs/hzn/service/usehello/Dockerfile
- test/docker/fs/hzn/service/usehello/start.sh
> Issue 2249 - Allow UDS run as non-root user

- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- i18n_translation/translated/anax.out.gotext_es.json
- i18n_translation/translated/anax.out.gotext_fr.json
- i18n_translation/translated/anax.out.gotext_it.json
- i18n_translation/translated/anax.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- locales/es/messages.gotext.json
- locales/fr/messages.gotext.json
- locales/it/messages.gotext.json
- locales/zh-CN/messages.gotext.json
> Translated message update for 1Q2021

- agent-install/edgeNodeFiles.sh
Added flags/features:
```
-r <registry/repo-path>     The agent images (both device and cluster) will be pulled from the specified authenticated docker registry. If this flag is set, you must also export the username and password for the registry in REGISTRY_USERNAME and REGISTRY_PASSWORD.
-g <tag>    Overwrite the default agent image tag. 
-b          Get the agent images from the horizon content tar file.
```
Now the script will pull from `docker.io/openhorizon` by default, or whatever registry is supplied with the `-r` flag. Using `-b` will gather the agent images as it does today, from the horizon tar file. 
Signed-off-by: Troy Fine <Troy.Fine@ibm.com>
> update edgeNodeFiles to pull agent images from registry

- test/gov/gov-combined.sh
- test/gov/service_configstate_test.sh
Signed-off-by: diru1100 rohitdandamudi.1100@gmail.com
Fixes issue: #1038
> Add e2edev service suspension test for policy case

- cli/dev/service.go
> Issue 2340 - 'hzn dev service log' cannot find service

- cli/cliutils/cliutils.go
- test/gov/hzn_dev_services.sh
> Issue 2318 - retrieve image digest by inspection

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Third PII drop for translation for 1Q2021

- anax-in-container/Dockerfile.ubi.amd64
- container/container.go
- test/gov/verify_agreements.sh
> Issue 2338 - remove parent specific network when parent is cancelled

- Makefile
- go.mod
> Issue 2346 - Update Anax to use sync service 1.5.3

- agreementbot/agreementworker.go
- agreementbot/basic_protocol_handler.go
- agreementbot/node_search.go
- anax-in-container/Dockerfile.ubi.amd64
- api/path_service_configstate.go
- test/gov/gov-combined.sh
- test/gov/service_configstate_test.sh
> Issue 2353 - agreement requeue causes extra agreements

- agent-install/edgeNodeFiles.sh
See https://github.com/open-horizon/anax/issues/2357
> Issue 2357: Have edgeNodeFiles.sh also put agent-install.sh in CSS

- agent-install/edgeNodeFiles.sh
> #2360 - Piped docker save command to gzip prior to outputting to file

- agent-install/agent-install.sh
- Added get_certificate function
- Fixed typo in log message
- Fixed issue for installing on MacOS
> Issue 2364; download cert if doesn't exist

- cli/locales/es/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
> Update to the message translation for the third PII for 1Q2021

- agreementbot/agreementbot.go
- agreementbot/basic_protocol_handler.go
- agreementbot/changes_worker.go
- agreementbot/prioritized_workqueue.go
- agreementbot/prioritized_workqueue_stats.go
- agreementbot/prioritized_workqueue_test.go
- anax-in-container/config/agbot.json.tmpl
- config/config.go
- config/constants.go
- events/events.go
- version/version.go
> Issue 2230 - avoid duplicate protocol message processing

- agent-install/README.md
> Update agent-install README.md

- css/horizonAuthenticate.go
> Issue 2402 - CSS code should not print node or user tokens

- cli/register/servicewait.go
Signed-off-by: Liang Wang <wanglcdl@cn.ibm.com>
> Issue 2377 - Enable translation for registration status

- docs/deployment_string.md
> Issue 2388 - document which deployment field settings require privilege to run

- cli/dev/utils.go
- container/container.go
> Issue 2343 - Unregister removes dev containers

- agreementbot/secure_api.go
- cli/exchange/org.go
- cli/hzn.go
- resource/authentication_manager.go
> Issue 2424 - Strict transport security not enforced for agbot secure API 

- agent-install/agent-install.sh
- Issue 2215: document `*_APPEND` env vars for experimental testing of other plaforms
- Issue 2390:
- Support `-f` (force) for deb and rpm platforms
- Add `-C` flag to install only the CLI, not the full agent
> Issues 2215 and 2390: document append env vars, support -f (force) for deb and rpm, add -C (cli only) flag

- agent-install/edgeNodeFiles.sh
Signed-off-by: Troy Fine <Troy.Fine@ibm.com>
> Issue 2406 - update edgeNodeFiles to be namespace agnostic

- Makefile
- go.mod
> Issue 2425 - Update Anax to use sync service 1.6.1

- Jenkinsfile
moving Jenkinsfile from lfedge/ci-management to anax/lfedge-jenkins
> Issue 2436 - Adding Jenkinsfile

- cli/exchange/business.go
> Issue 2411 - cli error for too many policies case

- anax-in-container/README.md
> Issue #2400 - support anax-in-container for linux

- cli/register/servicewait.go
> Issue 2418 - Agreement status not clear for registration

- cli/exchange/business.go
> Issue 2411 - No error given for too many deployment policies

- agent-install/agent-install.sh
> Issue 2327 - agent-install.sh assumes that a K3s cluster is amd64 only

- agent-install/agent-install.sh
See https://github.com/open-horizon/anax/issues/2448 for details.
> Issue 2448: add new agent-install flag combo for all-in-1

- Jenkinsfile
Signed-off-by: Mustafa <mmaj1976@gmail.com>
> issue 2436 - Updating Jenkinsfile

- agreementbot/secure_api.go
> Issue 2424 part 2: only add HSTS header for the https server.

- test/docker/fs/hzn/service/usehello/start.sh
> Issue 2459 - fix calls to dependency services

- agreementbot/secure_api.go
> Issue 2424 - only set the SSL header when SSL is enabled

- cli/cliutils/cliutils.go
- cli/sync_service/sync_service.go
> Issue 2392 - Ensure hzn dev leverages the hosts docker authentication

- test/Makefile
- test/docker/fs/etc/vault/config.hcl
- test/docker/fs/vault/agbot.acl.policy.hcl
- test/gov/gov-combined.sh
- test/gov/init_vault.sh
> Issue 2464 - boostrap the e2edev vault

- anax-in-container/horizon-container
> Issue 2493 - fix error in script

- agreementbot/agreementbot.go
- agreementbot/secrets/registry.go
- agreementbot/secrets/secrets.go
- agreementbot/secrets/vault/init.go
- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
- main.go
> Issue 2495 - secrets impl plugin framework

- agreementbot/agreementbot.go
- agreementbot/secure_api.go
> Issue 2498 - fix secure_api.go compile error

- Jenkinsfile
Signed-off-by: Mustafa <mmaj1976@gmail.com>
> issue 2436 - Updating node type in Jenkinsfile

- cli/cliutils/cliutils.go
- go.mod
> Issue 2188 - docker login credentials in the OS keyring

- test/Makefile
> Issue 2505 - Updated e2edev test against a pre-built remote environment

- pkg/mac/scripts/horizon-cli-uninstall.sh
@bmpotter Would you review this, I want try to fix #2269 , thanks
> Issue 2269 - remove hzn_bash_autocomplete.sh from the bash configure files

- cli/exchange/node.go
- cli/register/register.go
> Issue 2480 - Change 'hzn register -m <name>' to set the node name for existing nodes

- agreementbot/agreementbot.go
- agreementbot/secrets/secrets.go
- agreementbot/secrets/vault/http.go
- agreementbot/secrets/vault/init.go
- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
- config/config.go
> Issue 2515 - agbot panic when vault is not configured.

- agreementbot/activecontracts.go
- agreementbot/secrets/vault/http.go
- agreementbot/secrets/vault/init.go
- agreementbot/secrets/vault/vault.go
- api/api_attribute.go
- api/api_publickey.go
- cli/cliutils/cliutils.go
- cli/sdo/voucher.go
- cli/sync_service/sync_service.go
- css/horizonAuthenticate.go
- exchange/rpc.go
- imagefetch/imagepull.go
- test/docker/fs/hzn/service/hello/server.go
> Issue 2517 - Close response body for non-nil body

- anax-in-container/script/agbot_start.sh
> Issue 2463 - fixed the agbot log level

- .github/workflows/anax-build-test.yml
> Issue 2521 -Updated e2edev tests in action to not require Dockerhub login

- agreementbot/secrets/secrets.go
- agreementbot/secrets/vault/http.go
- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
- test/gov/agbot_apitest.sh
- test/gov/init_vault.sh
> Issue 2463 - Update agbot secrets api

- agent-install/agent-install.sh
Also added support to add `HZN_SDO_SVC_URL` to `agent-install.cfg` and `/etc/default/horizon`, because that is needed for similar reasons.
> Issue SDO-support 110: make HZN_AGBOT_URL optional in agent-install.sh

- Makefile
- go.mod
> Issue 2538 - Upgrade CSS/ESS to v1.6.3

- agent-install/agent-install.sh
- agent-install/agent-uninstall.sh
- Fixed some typos
- Fixed kubectl detection for agent-install and agent-uninstall 
- Tested on k3s, OCP, and edge device
> Fix issue with kubectl detection

- agreementbot/api.go
- agreementbot/secrets/secrets.go
- agreementbot/secure_api.go
- anax-in-container/config/anax.json
- anax-in-k8s/config/anax.json
- api/api_status.go
- apicommon/status.go
- cli/cliutils/cliutils.go
- cli/hzn.go
- cli/node/node.go
- config/config.go
- pkg/deb/horizon/etc/horizon/anax.json
- pkg/rpm/horizon/fs/etc/horizon/anax.json
- test/docker/fs/etc/colonus/anax-combined-no-cert.config.tmpl
- test/docker/fs/etc/colonus/anax-combined.config.tmpl
- test/docker/fs/etc/colonus/anax-combined2-no-cert.config.tmpl
- test/docker/fs/etc/colonus/anax-combined2.config.tmpl
- test/docker/fs/etc/colonus/anax-no-cert.config.tmpl
- test/docker/fs/etc/colonus/anax.config.tmpl
- test/gov/start_mgmt_hub.sh
> Issue 2465 -- Remove AgbotURL from anax config file for the agent.

- Makefile
- cli/hzn.go
- cli/sync_service/download.go
- cli/sync_service/object.go
- go.mod
- test/gov/resource_package.sh
- test/gov/sync_service_test.sh
> Issue 2485, 2486 - Adding data checksum in hzn mms object publish/download command

- test/gov/clean_css.sh
- test/gov/sync_service_test.sh
> Issue 2570 - Added additional e2edev MMS tests

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/basic_agreement_worker.go
- agreementbot/basic_protocol_handler.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/secrets/secrets.go
- agreementbot/secrets/vault/http.go
- agreementbot/secrets/vault/init.go
- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
- basicprotocol/protocol.go
- businesspolicy/business_policy.go
- common/secret_binding.go
- common/secret_binding_test.go
- exchange/pattern.go
- exchangecommon/secret.go
- policy/policy_file.go
- policy/policy_file_test.go
- producer/basic_protocol_handler.go
- test/Makefile
- test/gov/agbot_apitest.sh
- test/gov/init_vault.sh
- test/gov/setup_secrets.sh
> Issue 2469 2470 2578 - deploy secrets in a proposal

- cli/dev/service.go
- cli/hzn.go
> Issue 2393 - hzn dev service log should have an argument for the URL of the service to display

- cli/cliutils/cliutils.go
- cli/unregister/unregister.go
> Issue 2524 - hzn unregister command calls systemctl on MacOS

- anax-in-container/horizon-container
- api/path_node.go
- api/path_node_test.go
- cli/cliconfig/config.go
- cli/cliutils/cliutils.go
- cli/dev/image.go
- cli/dev/utils.go
- cutil/cutil.go
- docs/agent_container_manual_deploy.md
- docs/managed_workloads.md
- test/docker/fs/etc/agent-in-kube/horizon.env
- test/docker/fs/hzn/service/hello/start.sh
- test/docker/fs/hzn/service/usehello/start.sh
- test/gov/multiple_agents.sh
> Issue 2283 - anax and hzn should support HZN_NODE_ID in addition to HZN_DEVICE_ID

- docs/api.md
- docs/attributes.md
- docs/deployment_policy.md
- docs/deployment_string.md
- docs/model_policy.md
- docs/properties_and_constraints.md
- docs/service_def.md
Corrected some typos in anax docs
> Fix typos in anax docs

- agreementbot/api.go
- agreementbot/secrets/secrets.go
- agreementbot/secrets/vault/http.go
- agreementbot/secrets/vault/init.go
- agreementbot/secrets/vault/vault.go
- apicommon/status.go
- main.go
- test/gov/agbot_apitest.sh
* Add a lastVaultInteraction field to store last vault access
* Make a minor change in vault's init.go
Reference
#2533
> Issue 2533 - Update agbot health API with vault status

- css/horizonAuthenticate.go
> Issue 2514 - avoid 403 on some agbot CSS API calls

- test/gov/sync_service_test.sh
> Issue 2601 - Reduced the size of large model upload tests to 512MB

- agreementbot/object_manager.go
> Issue 2569 - Panic in agbot when mms objects deleted

- test/docker/Dockerfile
- test/gov/deployment_policies/userdev/netspeed.json
- test/gov/deployment_policies/userdev/netspeed_secrets.json
- test/gov/patterns/e2edev@somecomp.com/netspeed.json
- test/gov/patterns/e2edev@somecomp.com/netspeed_secrets.json
- test/gov/patterns/e2edev@somecomp.com/sall.json
- test/gov/patterns/e2edev@somecomp.com/sall_secrets.json
- test/gov/service_apireg.sh
- test/gov/service_defs/IBM/netspeed_2.3.0.json
- test/gov/service_defs/IBM/netspeed_2.3.0_secrets.json
- test/gov/service_defs/IBM/service-cpu_1.2.2.json
- test/gov/service_defs/IBM/service-cpu_1.2.2_secrets.json
- test/gov/service_defs/e2edev@somecomp.com/netspeed_2.3.0.json
- test/gov/service_defs/e2edev@somecomp.com/netspeed_2.3.0_secrets.json
- test/gov/service_defs/e2edev@somecomp.com/service-cpu_1.0.json
- test/gov/service_defs/e2edev@somecomp.com/service-cpu_1.0_secrets.json
- test/gov/setup_secrets.sh
> Issue 2614 - separated tests for secrets

- agreementbot/secrets/secrets.go
- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
- cli/secrets_manager/secrets_manager.go
- test/gov/hzn_secretsmanager.sh
> Issue 2600: the user private secrets are not working correctly in agbot API

- agreementbot/agreementbot.go
> Issue 2630 - Panic in the agbot from anax/events/secret_events.go:54

- cli/dev/secrets.go
- cli/dev/service.go
- cli/helm_deployment/helm_deployment.go
- cli/hzn.go
- cli/kube_deployment/kube_deployment.go
- cli/native_deployment/native_deployment.go
- cli/plugin_registry/plugin_registry.go
- containermessage/models.go
> Issue 2476 - Update hzn dev service new/start/stop to support secrets

- producer/basic_protocol_handler.go
- resource/secrets_manager.go
> Issue 2634 - Update service secrets in the agent filesystem

- agreementbot/basic_agreement_worker.go
- agreementbot/governance.go
- agreementbot/persistence/agreement.go
- agreementbot/persistence/bolt/agreement.go
- agreementbot/persistence/database.go
- agreementbot/persistence/postgresql/agreement.go
- agreementbot/secret_updater_test.go
- agreementbot/secrets/secrets.go
- cli/cliutils/cliutils.go
- cli/secrets_manager/secrets_manager.go
- cli/sync_service/object.go
- events/secret_events.go
- events/secret_events_test.go
- resource/secrets_manager.go
- test/docker/fs/etc/agbot/agbot-tmpl.json
> Issue 2646 - Remove duplicate secret update events

- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
- test/gov/hzn_secretsmanager.sh
> Issue 2580 - Support multi-part vault secret name

- Makefile
- container/container.go
- ess/cmd/edge-sync-service/main.go
- persistence/secret_status.go
- persistence/secrets.go
- resource/authentication_manager.go
- resource/resource_manager.go
- resource/resource_worker.go
- resource/secret_api.go
- resource/secret_api_authenticate.go
- resource/swagger.json
- test/docker/fs/hzn/service/cpu/Dockerfile
- test/docker/fs/hzn/service/leaf/Dockerfile
> Issue 2473 - Agent add /secret et. al. APIs, document APIs

- agreementbot/node_search.go
- governance/microservice.go
- persistence/secrets.go
- producer/basic_protocol_handler.go
- producer/producer_protocol_handler.go
- resource/secrets_manager.go
> Issue 2634 - Update dependent service secrets in the agent filesystem

- agent-install/agent-install.sh
- docs/agent_container_manual_deploy.md
> Fix typo in agent_container_manual_deploy.md

- resource/secret_api.go
- resource/swagger.json
> Issue 2657 - Format change of GET /secrets/secretName response

- go.mod
- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 2663 - 3Q2021 translation support

- agreementbot/secrets/vault/vault.go
- container/container.go
- governance/governance.go
- persistence/secret_status.go
- persistence/secrets.go
- producer/basic_protocol_handler.go
- resource/resource_manager.go
- resource/secret_api.go
- resource/secret_api_authenticate.go
- resource/secrets_manager.go
- test/gov/deployment_policies/userdev/netspeed_secrets.json
> Issue 2669 - Save service secrets with ms instance id instead of def.

- persistence/secrets.go
- resource/secrets_manager.go
> Issue 2677 - Handle service secret versions correctly

- agreementbot/agreementworker.go
- If multiple versions are in a policy, check compatibility of constraints in DP first
- Don't use workload_usage in DB unless needed
- Move getting maxHeartbeat until before we need to send a message
> Issue 2430 - avoid workload usage if not needed

- resource/secrets_manager.go
> Issue 2681 - Panic in the agent secrets manager

- agreementbot/agreementbot.go
- agreementbot/governance.go
- agreementbot/governance_test.go
- agreementbot/secure_api.go
- container/container.go
- governance/microservice.go
- microservice/microservice.go
> Issue 2686 - agbot governance needs to run more often

- agreementbot/secrets/secrets.go
- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
> Issue 2675 - Vault needs to use the user ID passed from the Exchange on iamapikey authentication

- agreementbot/agreementworker.go
> Issue 2693 - Remote e2edev test failure

- cli/locales/ja/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
> Issue 2663 - More translated files for the first drop for 3Q2021

- cli/exchange/service.go
> Issue 2699 - Fix typo

- docs/_includes/head.html
- docs/_includes/ogmeta.html
- docs/_layouts/page.html
Signed-off-by: Joe Pearson <joe.pearsonus.ibm.com@joes-mbp.usga.ibm.com>
Removed leading slash in page and metadata templates.  This should allow the banner image to appear.
> issue 2688 - remove extra leading slash

- persistence/secrets.go
> Issue 2711 - Unhandled error during secret cleanup

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 2663 - Second PII drop for 3Q2021

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 2663 - More messages for the second PII drop for 3Q2021

- cli/hzn.go
- cli/secrets_manager/secrets_manager.go
- test/gov/hzn_secretsmanager.sh
> Issue 2722 - hzn sm secret remove should have a prompt to confirm removal of the secret

- agreementbot/secrets/vault/vault.go
- agreementbot/secure_api.go
- cli/secrets_manager/secrets_manager.go
> Issue 2726 - hzn sm secret list is returning null instead of [] when there are no secrets

- test/gov/hzn_secretsmanager.sh
> Issue 2737 - Vault permissions for organization admins need to be fixed

- agreementbot/basic_agreement_worker.go
> Issue 2744 - panic in agbot on basicagreementreplyupdate

- agreementbot/agreementworker.go
- api/common_test.go
- api/path_node_configstate.go
- cli/exchange/business.go
- cli/exchange/business_test.go
- common/service_file.go
- compcheck/comp_check.go
- compcheck/policy_check.go
- compcheck/policy_check_test.go
- compcheck/secretbinding_check.go
- compcheck/secretbinding_check_test.go
- compcheck/userinput_check.go
- exchange/handlers.go
- exchange/service.go
- exchange/service_test.go
- governance/governance.go
- governance/microservice.go
- microservice/microservice.go
- test/gov/gov-combined.sh
> Issue 2708 - Service downgrading not working.

- abstractprotocol/proposal.go
- events/events.go
- exchange/agbot.go
- exchange/rpc.go
> Issue 2736 - ShortString() function doesn't add three dots

- version/version.go
> Update MINIMUM_EXCHANGE_VERSION to 2.82.0

- version/version.go
> Issue 2750 - Update MINIMUM_EXCHANGE_VERSION to 2.81.0

- test/Makefile
> Issue 2757: Made HZN_SDO_SVC_URL overridable

- container/container.go
- resource/secrets_manager.go
- test/Makefile
- test/gov/agbot_apitest.sh
- test/gov/deployment_policies/userdev/location.json
- test/gov/deployment_policies/userdev/location_secrets.json
- test/gov/gov-combined.sh
- test/gov/hzn_compcheck.sh
- test/gov/hzn_secretsmanager.sh
- test/gov/init_vault.sh
- test/gov/service_apireg.sh
- test/gov/service_secrets_test.sh
- test/gov/setup_secrets.sh
> Issue 2478 - Add test cases in e2edev to support vault secrets

- agent-install/agent-install.sh
See [issue 2753](https://github.com/open-horizon/anax/issues/2753) for details.
> Issue 2753: agent-install.sh restart agent if cert changed

- cli/hzn.go
- cli/sdo/key.go
- test/gov/hzn_sdo.sh
> Issue 2761 - The hzn sdo keys sub-command should be singular

- cli/service/service.go
> Issue 2766 - hzn service log displays first instance of service name substring instead of exact string

- governance/microservice.go
- persistence/secrets.go
- test/gov/gov-combined.sh
- test/gov/service_secrets_test.sh
> Issue 2782 - e2edev failure on service secret tests

- cli/cliutils/cliutils.go
> Issue 2780 - Agent API error gives incorrect status URL for Linux distros

- agent-install/edgeNodeFiles.sh
> Issue 2787: EdgeNodeFiles.sh does not add HZN_SDO_SVC_URL to agent-istall.cfg

- cli/cliutils/stdout_logging.go
- cli/dev/service.go
- cli/service/service.go
> Issue 2778 - 'hzn service log' does not work in some cases

- agreementbot/secrets/vault/vault.go
- test/gov/gov-combined.sh
- test/gov/hzn_secretsmanager.sh
> Issue 2774 - non-root user cannot list a specific org level secret

- container/container.go
> Issue 2808 - Intermittent e2edev service secret test failure

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/anax.out.gotext_fr.json
- i18n_translation/translated/anax.out.gotext_it.json
- i18n_translation/translated/anax.out.gotext_ja.json
- i18n_translation/translated/anax.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
- locales/fr/messages.gotext.json
- locales/it/messages.gotext.json
- locales/ja/messages.gotext.json
- locales/pt-BR/messages.gotext.json
> Issue 2663 - Translated files from the 3rd PII

- exchangecommon/secret.go
- exchangecommon/secret_test.go
- policy/policy_manager.go
- policy/workload.go
> Issue 2812 - remake agreements when secret binding changes

- exchange/cache.go
- exchange/service.go
> Issue 2792 - stop returning ptrs to stack variables

- cli/samples/privileged_node_policy.json
> Issue 2827 - sample for priv mode node policy

- Makefile
> Updated versions for next release: Anax 2.30.0 and CSS/ESS 1.7.0

- go.mod
> update sync service version in go.mod to v1.7.0

- Makefile
- cli/hzn.go
- cli/sync_service/object.go
- go.mod
…ts for Listing objects command
> Issue 2830 - Add a flag to only show 'deleted' or 'not deleted' objec… 

- test/gov/hzn_sdo.sh
> Issue 2814 - e2edev SDO tests fail when /etc/default/horizon exists

- cli/sdo/key.go
> Issue 2825 - Some messages did not use msgPrinter in cli to print out

- agreementbot/secure_api.go
- cli/sdo/key.go
- cli/sync_service/object.go
- common/pattern_file.go
- common/service_file.go
- events/events.go
- exchangecommon/secret.go
- exchangecommon/secret_test.go
- microservice/microservice.go
> Issue 2760 - ExchangeToken displayed in logs

- cli/cliutils/stdout_logging.go
> Issue 2826 - "hzn service log" command slow to provide output

- cli/dev/servicepolicy.go
- cli/exchange/service.go
- externalpolicy/external_policy.go
> Issue 1667 - Add label and description to node and service policy

- README.md
> Issue 2847 - Add PR guidelines to anax README

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/changes_worker.go
- agreementbot/object_manager.go
- agreementbot/persistence/postgresql/agreement.go
- agreementbot/policy.go
- exchange/changes.go
- exchange/css.go
- exchange/rpc.go
- exchange/service.go
- Avoid agbot generating huge log messages
- Fix a typo in some messages
- In a couple of critical paths, check if V(5) logging is prior to creating log message for optimization
> Issue 2574 - Avoid huge log messages

- README.md
Fixed the link to test dir with correct address.
Signed-off-by: Marhababanu Chariwala <marhabac33@gmail.com>
> issue-2857: Fixed broken link in README

- Makefile
- anax-in-container/Dockerfile.alpine.amd64
- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- anax-in-container/Dockerfile.ubi.ppc64el
- anax-in-container/Dockerfile.ubi.s390x
- anax-in-container/Dockerfile_agbot.ubi
- anax-in-k8s/Dockerfile.ubi.amd64
- anax-in-k8s/Dockerfile.ubi.arm64
- anax-in-k8s/Dockerfile.ubi.ppc64el
- css/image/cloud-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
- test/docker/Dockerfile
Signed-off-by: Igor Kolinko <ikolin@softserveinc.com>
> Issue 2038 - Dockerfile performance improvements

- cli/secrets_manager/secrets_manager.go
> Issue 2843 - secret list return null when no secrets

- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
> Issue 2864 - Fixed multi-line command syntax issue

- cli/cliutils/cliutils.go
- cli/sync_service/download.go
> Issue 2611 - MMS download CLI should present percentage of data that has been downloaded

- doc/deployment_string.md
- doc/managed_workloads.md
- doc/service_def.md
@joewxboy, @Rene-Ch1 and @dabooz 
Please review the changes.
> deleted /doc for issue #2868

- semanticversion/version.go
- semanticversion/version_test.go
> Issue 2935 - semantic versioning fails when version is before the given range

- cli/exchange/nmp.go
- cli/hzn.go
- exchange/node_management_policy.go
- exchangecommon/node_management_policy.go
- test/README.md
- test/gov/gov-combined.sh
- test/gov/hzn_nmp.sh
> Issue 2880 - AgentAutoUpgrade: Add CLI commands to add/update/remove/list node management policy

- api/api_node.go
- api/messages.go
- cli/exchange/nmp.go
- cli/hzn.go
- exchange/node_management_policy.go
- exchangecommon/node_management_policy.go
- semanticversion/version_test.go
> Issue 2940 - Building Anax message catalog results in error

- test/gov/hzn_nmp.sh
> Issue 2942 - Fix hzn exchange nmp CLI e2edev error

- agreementbot/policy.go
> Issue 2446 - mms and service name with underscore fails

- test/gov/hzn_reg.sh
> Issue 2946 - Missing quotes in node_policy.json file for e2edev

- go.mod
- go.sum
> Issue 2949 - fix make i18n errors

- cli/hzn.go
> Issue 2952 - MMS CLI should be usable within a container deployed to k8s

- api/api.go
- api/api_management.go
- api/path_management_nextjob.go
- api/path_management_nextjob_test.go
- api/path_management_status.go
- api/path_management_status_test.go
- events/events.go
- nodemanagement/node_management_worker.go
- persistence/node_management_status.go
> Issue 2885 - AgentAutoUpgrade: Anax API to list agent upgrade jobs and status

- agreement/agreement.go
- governance/governance.go
> Issue 2955 - Eliminate 1 call from agent

- api/api.go
- api/api_management.go
- api/path_management_nextjob.go
- api/path_management_nextjob_test.go
- api/path_management_status.go
- api/path_management_status_test.go
> Issue 2961 - AgentAutoUpgrade: Fix anax nodemanagement API panic

- cli/exchange/agbot.go
- cli/exchange/nmp.go
- cli/exchange/node.go
- cli/hzn.go
- test/gov/gov-combined.sh
- test/gov/hzn_nmp.sh
> Issue 2881 - AgentAutoUpgrade: Add nmp check CLIs

- cli/exchange/nmp.go
- exchangecommon/node_management_policy.go
> Issue 2969 - hzn exchange nmp add remove --no-constraints flag on pattern case

- api/messages.go
- api/path_management_status.go
- persistence/eventlog_const.go
> Issue 2964 - AgentAutoUpgrade: add eventlog for node management status changes

- test/gov/hzn_nmp.sh
> Issue 2958 - make nmp CLI e2e tests more versatile

- agent-install/agent-install.sh
- cli/samples/user_input.json
> Issue 2973 - Add new RH releases to agent-install

- Makefile
- cli/cliutils/cliutils.go
- cli/hzn.go
- cli/sdo/key.go
- cli/sdo/voucher.go
- cli/sync_service/object.go
- config/constants.go
- config/file_sync_service.go
- go.mod
- go.sum
- resource/resource_manager.go
- test/gov/sync_service_test.sh
> Issue 2962 - hzn mms object publish should support chunk uploading

- api/path_management_status.go
> Issue 2979 - Fix eventlog output for nmp status PUT API

- config/file_sync_service.go
> Issue2962 - hzn mms object publish should support chunk uploading

- Makefile
- go.mod
- go.sum
> Issue 2985 - Anax build fails on armhf architecture

- agreement/agreement.go
- api/api_node.go
- exchange/rpc.go
- exchangesync/node.go
- governance/shutdown.go
> Issue 2983 - Agent version missing from node object in exchange

- download/download_worker.go
- exchange/node_management_status.go
- governance/shutdown.go
- nodemanagement/node_management_worker.go
- persistence/node_management_policy.go
- persistence/node_management_status.go
> Issue 2977 - AgentAutoUpgrade: NMP worker clean up on unregistration

- agent-install/agent-install.sh
- anax-in-container/horizon-container
- cli/hzn.go
- cli/unregister/unregister.go
- pkg/deb/horizon-cli/etc/horizon/hzn.json
- pkg/rpm/horizon-cli/fs/etc/horizon/hzn.json
> Issue 2217 - AgentAutoUpgrade: Improve support for running the anax container on linux edge node

- agent-install/edgeNodeFiles.sh
-    Don't push agent-install.cfg or agent-install.crt if they already exist in CSS as object type agent_files
-   Push artifact to old object type and also new object type for agent upgrade
-    Generate an upgrade manifest listing artifacts that were pushed to CSS and publish that file in CSS too
> Issue 3006 - edgeNodeFiles enhancements

- agent-install/README.md
- agent-install/agent-install.sh
> Issue 3010 - update agent-install readme

- cli/sync_service/object.go
> Issue 3015 - hzn mms object publish hangs when timeout is short

- exchange/rpc.go
> Issue 3018 - Retry on broken pipe

- Makefile
- go.mod
- go.sum
> Issue 100 - CSS API to retrieve all object types under a given org

- cli/hzn.go
- cli/sync_service/object.go
> Issue 3005 - AgentAutoUpgrade: hzn mms CLI lists all the object types for an org

- agent-install/agent-install.sh
- cli/unregister/unregister.go
- exchangesync/node.go
> Issue 3026 - AgentAutoUpgrade: force reinstall and verify cert file

- cli/hzn.go
- cli/node_management/agentfiles.go
> Issue 3002 - AgentAutoUpgrade: hzn command to list agent files/types from mms

- cli/hzn.go
- cli/node_management/manifest.go
> Issue 3001 - AgentAutoUpgrade: hzn command to create and list manifest files

- agent-install/agent-install.sh
- Change parameters on netstat  command
> Issue 3035 - agent-install.sh port check fails

- agent-install/agent-auto-upgrade.sh
- agent-install/agent-install.sh
- anax-in-container/horizon-container
- cli/hzn.go
- cli/node_management/agentfiles.go
- cli/node_management/manifest.go
- pkg/deb/.gitignore
- pkg/deb/Makefile
- pkg/deb/horizon/DEBIAN/postinst
- pkg/deb/horizon/DEBIAN/prerm
- pkg/mac/Makefile
- pkg/mac/scripts/horizon-cli-uninstall.sh
- pkg/mac/scripts/postinstall
- pkg/rpm/horizon-cli/.gitignore
- pkg/rpm/horizon-cli/Makefile
- pkg/rpm/horizon/fs/etc/horizon/hzn.json
- pkg/rpm/horizon/horizon.spec
> Issue 2895 - AgentAutoUpgrade: Packaging update for agent auto upgrade

- cli/exchange/nmp.go
- nodemanagement/commands.go
- nodemanagement/node_management_worker.go
> Issue 2886 - AgentAutoUpgrade: node management worker handle nmp updates

- agent-install/edgeNodeFiles.sh
> Issue3047: Missing files from agent_software_files

- cli/node_management/agentfiles.go
- cli/node_management/manifest.go
> Issue 3051 - AgentAutoUpgrade: remove logic for labeling agent file types with latest

- cli/node_management/manifest.go
> Issue 3057 - AgentAutoUpgrade: hzn nm manifest panic when getting non-public manifests

- cli/node_management/agentfiles.go
- download/download_worker.go
- exchange/node_management_status.go
- exchangecommon/node_management_status.go
- externalpolicy/builtin_properties.go
- nodemanagement/commands.go
> Issue 2978 part 2 - fix schema issue and cluster package download issue

- .github/ISSUE_TEMPLATE/Other.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-update.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR is for the issue no #3048
This PR Contains
* Added Issues Templates
* Added PR Templates
> feat : Added Issue templates and PR templates

- agent-install/agent-install.sh
- anax-in-container/horizon-container
- cli/cliutils/cliutils.go
- cli/dev/image.go
- cli/dev/utils.go
- cli/unregister/unregister.go
- container/container.go
- containermessage/models.go
- cutil/cutil.go
- pkg/rpm/horizon/horizon.spec
Changes to support podman v4
code changes to detect docker vs podman
agent-install.sh to detect docker or podman
horizon.spec so rpm can install with docker or podman
horizon-container to work with podman
Fixes # https://github.com/open-horizon/anax/issues/3062
e2edev passed
ran agent install on docker and ubuntu envs
ran agent install on a edge cluster env
...
- [ x] New and existing unit tests pass …
> Issue 3062 - podman support

- api/api_management.go
- api/path_management_status.go
- api/path_management_status_test.go
This PR fixes issue #3004 by refactoring the structure that is filled when a user invokes a PUT request on the agent API: `/nodemanagement/status/<nmp-name>`. This allows the user to create a status json and update the status for a NMP stored in the local db without having to use a separate struct. Both the local NMP and API now use the following status structure:
```
{
"userdev/<nmp-name>": {
"agentUpgradePolicyStatus": {
"scheduledTime": "",
"startTime": "",
"upgradedVersions": {
"softwareVersion": "",
"certVersion": "",
"configVersion": ""
},
"status": "",
"workingDirectory": ""
},
"agentUpgradeInternal": {}
}
}
```
Fixes #3004
There was not much testing to be done as this issue was already …
> Issue 3004 - AgentAutoUpgrade: CLI and agent API  handles node management status schema change

- .github/workflows/anax-build-test.yml
> Issue 3085 - Add maintenance branch to PR build workflow

- cli/sync_service/object.go
- exchange/rpc.go
Sent to Sanjeev to test  in his environment
...
- [ x] I have tagged the reviewers in a …
> Issue 3081 - retry on DNS error

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 3098 - PII files for translation for v2.29

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> First translation message drop for 2Q 2022

- container/container.go
> Issue 3112 - agent panic when docker InspectContainer returns wrong info

- cli/sync_service/object.go
Reading the response body if present is needed to re-use the HTTP client connection
Fixes # https://github.com/open-horizon/anax/issues/3115
Monitored agent connections while uploading to make sure only 1 was used
...
- [ x] I have tagged the reviewers in a comment below incase my pull …
> Issue 3115 - mms publish reuse connection

- Makefile
- cli/sync_service/object.go
- go.mod
- go.sum
Update to use CSS v1.8.7
Change agent to accommodate CSS changes
Fixes # https://github.com/open-horizon/anax/issues/3117
Tested with and without integrity and with streaming
...
- [ x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ x] …
> Issue 3117 - Use new CSS

- api/path_management_nextjob_test.go
- api/path_management_status_test.go
- api/path_node.go
- api/path_node_configstate_test.go
- api/path_node_policy_test.go
- api/path_node_test.go
- api/path_service_config_test.go
- api/path_service_configstate_test.go
- cli/exchange/node.go
- download/download_worker.go
- download/download_worker_test.go
- events/events.go
- exchange/handlers.go
- exchangecommon/node_management_status.go
- exchangesync/node_policy_test.go
- externalpolicy/constraint_expression.go
- microservice/microservice_test.go
- nodemanagement/node_management_worker.go
- nodemanagement/node_management_worker_test.go
- persistence/device.go
- persistence/node_management_status.go
Tested in e2edev
Added unit tests that will fail until the code to call agentFileVersions is uncommented
...
> Issue 2888 - AgentAutoUpgrade: Resolve conflicts for nmps

- go.mod
- go.sum
Updated golang dependencies `golang.org/x/net` and `golang.org/x/term`
Fixes #3127 
Tested on Jenkins pipelines on Linux build machine.
...
> Issue 3127 - Unable to build v2.29 maintenance branch

- anax-in-container/horizon-container
> Modified a message for horizon-container script

- cli/exchange/nmp.go
- cli/exchange/node.go
- cli/hzn.go
- exchangecommon/node_management_status.go
This PR adds the `hzn exchange nmp status` and `hzn exchange node management status` CLI commands to get NMP statuses from the exchange. 
Fixes #2959, #2882
All of the commands were run with their various flags to ensure that the output is formatted correctly and returns the correct information.
> Issue 2959 - AgentAutoUpgrade: Add nmp status CLI command

- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 3103 - Second translation file drop for 2Q2022

- cli/exchange/nmp.go
- cli/exchange/node.go
- cli/hzn.go
This PR fixes the output of the `hzn exchange node management status` command which was using the same alias as the `hzn exchange node management list` command, and therefore giving the same output.
This PR also introduces the `--policy` flag to the `hzn exchange node management status` command which filters the output to display information only about the given NMP. Likewise, a `--node` flag was added to the `hzn exchange nmp status` command for filtering output to display information only about the given node.
Finally, this issue fixes some formatting issues with the `hzn exchange node management status` and `hzn exchange node management list` commands. They now output maps instead of arrays to better represent the data being displayed. …
> Issue 3136 - fix hzn ex node mgmt list/status help output

- Makefile
Fixed Dockerfile name
Fixes #3138 
Internal Jenkins build
...
> Issue 3138 - Fixed incorrect Dockerfile filename.

- agent-install/agent-install.sh
> Issue 3080 - agent-install.sh uses new types for agent files

- cli/exchange/nmp.go
- cli/exchange/node.go
- cli/sync_service/object.go
- exchange/css.go
- exchange/rpc.go
- exchangecommon/node_management_status.go
> Issue 3144 - Agent handle http code 429 for exchange and CSS calls

- Makefile
- cli/node_management/manifest.go
- css/horizonAuthenticate.go
- go.mod
- go.sum
This change is to use the updated ACL for manifest in sync service. So that: 
- Node credential should able be used to read manifest under its org
- exchange regular use should be able to read manifest under his org but shouldn't be able to create manifest
- exchange admin should be able to read/write manifest under his org
Tested in e2edev environment
...
> Issue 3146 - Update css authentication to use new ACL for manifest

- agreementbot/agreementworker.go
> MMS fails with service with underscore

- agent-install/agent-install.sh
User installed with Ubuntu 22.04
...
- [x ] I have performed a self-review of my own code
> Issue 3157 - Support for Ubuntu 22.04

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
> Issue 3103 - Second translated messages for 2Q2022

- agent-install/agent-auto-upgrade.sh
- agent-install/agent-install.sh
- anax-in-container/horizon-container
- api/api_int_test.go
- api/api_management.go
- api/path_management_status.go
- api/path_node_policy_test.go
- common/node_management.go
- events/events.go
- nodemanagement/node_management_worker.go
> Issue 3164 - Bug: node management status out of sync

- agreementbot/api.go
- api/api_management.go
- api/api_status.go
- api/path_management_status.go
- api/path_management_status_test.go
- api/path_node_policy_test.go
- apicommon/status.go
- common/node_management.go
- exchangecommon/agentfiles.go
- exchangesync/node.go
- nodemanagement/node_management_worker.go
- persistence/device.go
- version/version.go
> Issue 3168 - Set cert version and config version to node in the exchange

- config/config.go
Fixes # 3170
tested in e2edev
...
> Issue #3170 - Bug: K8sCRInstallTimeoutS default value not being used

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 3103 - Third translation file drop for 2Q2022

- agent-install/k8s/auto-upgrade-cronjob-template.yml
- anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh
This PR fixes several issues found when testing the integration of the k8s auto upgrade worker and the rollback script. These issues include:
- The cronjob pod now uses a mount point on the same PVC as the agent pod
- The cronjob works on a local path to the status.json file mounted to the shared PVC
- Edge cases for rolling back the agent image when it is in a panic state were added
- Logging messages were added
The changes were tested by running a full loop run of the k8s worker on various states including the following:
- Image, cert and/or config needs an update
- None of the above need an update
- The image was updated but is in a panic state
- The image was downgraded but is …
> Issue 3176 - Fix agent auto upgrade k8s cronjob integration

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/anax.out.gotext_de.json
- i18n_translation/translated/anax.out.gotext_fr.json
- i18n_translation/translated/anax.out.gotext_it.json
- i18n_translation/translated/anax.out.gotext_ja.json
- i18n_translation/translated/anax.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
- locales/de/messages.gotext.json
- locales/fr/messages.gotext.json
- locales/it/messages.gotext.json
- locales/ja/messages.gotext.json
- locales/ko/messages.gotext.json
> Issue 3103 - Third translated messages updated for 2Q2022

- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 3103 - minor changes for 3 messages for translation.

- agent-install/agent-install.sh
> Issue #3193 - Bug: agent install log output

- test/gov/gov-combined.sh
This PR comments out NMP CLI tests for the time being.
Fixes #3204
It does not need testing
> Issue 3204 - Comment out NMP CLI tests

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/anax.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
- locales/ja/messages.gotext.json
> Issue 3103 - updated translated messages for 2Q2022

- agent-install/agent-install.sh
- agent-install/agent-uninstall.sh
- pkg/rpm/horizon/horizon.spec
> Issue 3219 - Bug: cron job is missing after an upgrade on rhel

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
> Issue 3103 - more updated translated messages

- agent-install/README.md
- agent-install/agent-install.sh
Support for RHEL 8.6
Fixes #3229
Podman 4.x is now experimental on RHEL 8.6 and should be tested.
> Issue 3229 RHEL8.6 Support

- .github/ISSUE_TEMPLATE/new-arch.yml
- .github/ISSUE_TEMPLATE/new-distro.yml
Issue Template / Checklists to add support for 
- a new Linux distro release (RHEL 8.x / 9.x, Ubuntu, Fedora, Yocto, Debian)
- a new microprocessor architecture (RISC-V or Fedora aarch64)
Fixes #3232
> New Distro & Arch Issue Templates

- nodemanagement/node_management_worker.go
> Issue #3236 - Bug: nmp download failed right after unregister

- agent-install/agent-install.sh
Add `redhatenterprise` as a Red Hat Linux distro variant.
Fixes #3246 
Tested in a RHEL 8.6 KVM instance
...
> Issue 3246 - Support redhatenterprise distro variant

- agent-install/agent-auto-upgrade.sh
- exchangecommon/node_management_policy.go
> Issue 3261 - AgentAutoUpgrade: show upgrade error in rollback status

- agent-install/README.md
- agent-install/agent-install.sh
- pkg/rpm/README.md
Fixes #3257 #3256 
I have tested the agent-install.sh on my Fedora 36 workstation
> Issue 3257 fedora36 support

- cli/exchange/nmp.go
- cli/sync_service/object.go
- download/download_worker.go
- nodemanagement/node_management_worker.go
- test/gov/sync_service_test.sh
> Issue 3266 - Bug: error message with command hzn mms object list -d

- governance/shutdown.go
- nodemanagement/commands.go
- nodemanagement/node_management_worker.go
> Issue #3265 - Bug: the nmp does not get reevaluated after pattern change

- cli/exchange/nmp.go
This PR adds a check in the `hzn exchange nmp add` command to ensure that a correct manifest is specified if the AgentAutoUpgradePolicy struct is defined within the NMP.
Fixes #3276
This was tested by running the command with an NMP that used a non-existing manifest to make sure it threw the correct error. The same command was tested with a correct manifest to ensure it still worked as it did before this change.
> Issue 3276 - Add check to hzn ex nmp add command to ensure manifest exists in CSS

- exchangecommon/node_management_status.go
> Issue #3286 - Bug: startWindow in NMP not having the desired effect

- agent-install/agent-auto-upgrade.sh
- cli/exchange/nmp.go
- clusterupgrade/cluster_upgrade_worker.go
- docs/node_management_status.md
- exchangecommon/node_management_status.go
- nodemanagement/node_management_worker.go
> Issue 3290 - Avoid certain words used in messages

- docs/node_management.md
> fix typo in docs/node_management.md

- cli/exchange/nmp.go
This PR fixes the `--applies-to` flag for the `hzn exchange nmp add` CLI command. Before this fix, the flag failed to check the case where an NMP specifies pattern(s), but the node is registered with a policy with no constraints.
The flag logic now uses the same validation function that the node_management_worker uses to check NMP compatibility.
Fixes #3309 
This was tested by running the known problem-case and verifying the correct output is now returned. The base cases were also rechecked.
> Issue 3309 - Bug: NMP with list of patterns shows that it would be applied to many nodes running a policy

- externalpolicy/builtin_properties.go
This PR fixes the bug that causes podman anax-in-container agents to fail during agent auto upgrade download stage. This was due to the built-in property `openhorizon.containerized` being set to false instead of true.
The node policy initialization - the process that set the built-in properties - now check to see if the DOCKER_NAME environment variable is defined on the agent container. This is only set when running anax-in-container, and is therefore a more comprehensive way to check for container agents on both docker and podman.
Fixes #3298
This was tested by installing an anax-in-container agent running on podman using this new binary and running an agent auto upgrade job. The agent was able …
> Issue 3298 - Bug: AgentAutoUpgrade fails on podman running anax-in-container

- agent-install/agent-install.sh
For podman, check the networkbackend and issue a warning if it is not netavark
Fixes # https://github.com/open-horizon/anax/issues/3268
Ran script on RHEL 9.0 environment
...
- [ x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ x] I …
> Issue3268 - Check podman network stack

- exchangecommon/node_management_status.go
- nodemanagement/node_management_worker.go
This PR extends the fix in PR #3287 which fixed the startWindow of every NMP receiving the same random value. After that fix, the first run of an NMP across a set of nodes would stagger the start time if it specified a startWindow. However, if that NMP also specified a manifest that tracks the "latest" files, the subsequent runs would not stagger the start time.
The reason for this is that the start time would have already passed, so the NMP would kick off as soon as the new files are added to the CSS. Now, when the node management worker reevaluates the NMP's, it will add on a random value to the current time based off startWindow and make that the new start time.
Fixes #3286 
This was tested …
> Issue 3286 - Bug: startWindow in NMP not having the desired effect

- exchange/css.go
Need longer timeout for download from CSS
Fixes # #3334 
- [x ] Bug fix (non-breaking change which fixes an issue)
Built and tested upgrades in my scale env
...
- [ x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) …
> Issue_3334 Failure to download files

- cli/node_management/agentfiles.go
- cli/node_management/manifest.go
- exchange/css.go
> Issue 3348 - Bug: deleted manifest still shown in list

- Makefile
- go.mod
- go.sum
> Issue3348 - Bug: deleted manifest still shown in list

- Makefile
- go.mod
- go.sum
> Issue 3340 - Bug: CSS getting an OOM during agent auto upgrade

- kube_operator/client.go
> Issue #3350 - Bug: anax crash with bad operator.tar.gz

- agent-install/agent-install.sh
Strip trailing / from HZN_EXCHANGE_URL if it exists to prevent the curl command from failing
Fixes #3357 
Built and tested with a w/o a trailing slash
...
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- [x ] I have checked my code and corrected any misspellings
- [x ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x ] I have signed the commit message …
> Issue3357 - Strip trailing slash on exchange url

- cli/exchange/nmp.go
- cli/hzn.go
> remove debug message in cli/exchange/nmp.go

- Makefile
- go.mod
- go.sum
> Issue 3340 - Bug: CSS getting an OOM during agent auto upgrade (part2)

- docs/all-in-1-setup.md
- docs/api.md
- docs/cluster_install.md
- docs/node_management_overview.md
- docs/node_management_policy.md
- docs/node_management_status.md
- kube_operator/kubeworker.go
This PR adds documentation for the Agent Auto Upgrade process as well as set-up and install instruction for edge clusters.
Fixes #3341
> Issue 3341 - Agent Auto Upgrade and Cluster Install Open Horizon Documentation

- common/node_management.go
- exchangecommon/node_management_status.go
- externalpolicy/builtin_properties.go
- nodemanagement/node_management_worker.go
> Issue 3352 - Bug: moved 2 built-in properties to low level incorrectly

- governance/shutdown.go
- nodemanagement/node_management_worker.go
The `DeleteNodePolicy` part is removed from the `deletePolicyFiles` function. It only affects the pattern change case because there is another separate call to the `DeleteNodePolicy` in the other case.
...
> Issue 3386 - Bug: node policy missing after pattern change

- cli/native_deployment/native_deployment.go
- container/container.go
- containermessage/models.go
Signed-off-by: Ranine Haidous <ranine.haidous@ibm.com>
...
> Adding docker options for palmetto

- cli/hzn.go
- cli/register/register.go
- containermessage/models.go
- docs/api.md
- policy/policy_file_test.go
- policy/test/pfcompat2/device1.policy
- policy/test/pfcompat2/device2.policy
- policy/test/pfcompat2/expecting.policy
- policy/test/pfcompat2/merged.policy
- policy/test/pfcreate/created.policy
- policy/test/pfcreate/expecting.policy
- policy/test/pfmerge1/expecting.policy
- policy/test/pftest/echo.policy
- policy/test/pftest/test1.policy
- policy/test/pftest/test2.policy
> Issue 3372 - HAGroup: Add --hagroup flag for 'hzn register' command

- agreementbot/agreementworker.go
- agreementbot/basic_protocol_handler.go
- agreementbot/consumer_protocol_handler.go
- docs/agreement_bot_api.md
> Issue 3366 - HAGroup: Undo setting ha_partners for agreement object in agbot

- cli/deploycheck/allcomp.go
- cli/deploycheck/policy.go
- cli/deploycheck/secretbinding.go
- cli/deploycheck/userinput.go
- cli/hzn.go
- cli/register/servicewait.go
> Issue 3374 - HAGroup: Support ha group for hzn deploycheck commands

- test/Makefile
- test/README.md
- test/gov/apireg.sh
- test/gov/gov-combined.sh
- test/gov/ha_test.sh
- test/gov/hello_apireg.sh
- test/gov/ns_apireg.sh
- test/gov/service_upgrading_downgrading_test.sh
- test/gov/start_node.sh
- test/gov/utils.sh
> Issue 3375 - HAGroup: Add e2edev test cases

- clusterupgrade/cluster_upgrade_worker.go
- download/download_worker.go
- nodemanagement/node_management_worker.go
- worker/worker.go
> Issue 3403 - Bug: Node tokens should not be printed in log messages

- agreementbot/persistence/bolt/ha_groups.go
- agreementbot/persistence/ha_groups.go
- agreementbot/persistence/postgresql/ha_groups.go
- cli/hzn.go
- cli/sdo/voucher.go
> Issue 3402,3411 - Add HA group and user input to SDO voucher import

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/changes_worker.go
- agreementbot/commands.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/governance.go
- agreementbot/persistence/bolt/ha_group_workload.go
- agreementbot/persistence/bolt/workload_usage.go
- agreementbot/persistence/database.go
- agreementbot/persistence/ha_group_workload.go
- agreementbot/persistence/postgresql/ha_group_workload.go
- agreementbot/persistence/postgresql/init.go
- agreementbot/persistence/postgresql/workload_usage.go
- agreementbot/persistence/workload_usage.go
- events/events.go
- exchange/cache.go
- exchange/changes.go
- exchangecommon/ha_group.go
> Issue3368 - HAGroup: Agbot monitor and cache nodes for HAGroup

- agent-install/agent-install.sh
>  Issue 3420 - HAGroup: Add ha-group flag for agent-install.sh

- agreementbot/agreementbot.go
- agreementbot/persistence/bolt/ha_group_node_management.go
- agreementbot/persistence/database.go
- agreementbot/persistence/ha_group_node_management.go
- agreementbot/persistence/postgresql/ha_group_node_management.go
- exchange/rpc.go
- exchangecommon/node_management_status.go
> Issue #3369 - HAGroup: Agbot update ha nmp table with ha group changes

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/governance.go
- agreementbot/persistence/bolt/ha_group_workload.go
- agreementbot/persistence/database.go
- agreementbot/persistence/postgresql/ha_group_workload.go
- cli/samples/node_policy_input.json
- cli/samples/privileged_node_policy.json
- test/gov/multiple_agents.sh
Fixes #3368 and some updates for handling multi-agbot and database partition.
...
> Issue 3368 - HAGroup: fix ha group change handler and handle multiple agbots

- test/gov/service_upgrading_downgrading_test.sh
> Set variable for e2edev service upgrading/downgrading test

- agent-install/agent-install.sh
- agent-install/edgeNodeFiles.sh
Executed to push arm64 anax in container and installed container image on agent
...
- [ x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ x] I have signed the commit …
> Enable arm64 anax-in-container install from CSS

- anax-in-container/horizon-container
- anax-in-container/script/anax.service
Built container and tested using default fsspath and a changed path
...
- [ x] I have tagged the …
> Issue3468 - anax container needs to honor HZN_VAR_RUN_BASE

- test/gov/sync_service_test.sh
> fix e2edevtest

- docs/attributes.md
- docs/index.md
This PR should really fix the broken links...
Fixes  #3482
> Issue #3482 - Fix broken links

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/persistence/database.go
- agreementbot/persistence/workload_usage.go
- agreementbot/secrets/vault/http.go
- cli/cliutils/cliutils.go
- config/collaborators.go
- config/config.go
- config/constants.go
- css/horizonAuthenticate.go
- cutil/cluster.go
- exchange/rpc.go
> Issue 3452 - Bug: service not get upgraded in a multi-agbot env

- cli/cliutils/cliutils.go
- cli/cliutils/cliutils_test.go
- cli/exchange/org.go
Added checks to verify that Organization doesn't contains invalid characters: underscores (_), comas (,), blank spaces ( ), single quotes ('), or question marks (?)."
Fixes #2765
Tested the regex with combination of all the valid and invalid strings to see the expected outcome.
...
> Issue 2765 - Added validation for org before create & deletion

- README.md
- agent-install/k8s/auto-upgrade-cronjob-template.yml
- test/README.md
> Issue 3505 - Cluster Agent Cronjob failed to run in k3s

- .github/workflows/anax-build-test.yml
- go.mod
- go.sum
> Security Scan

- agent-install/edgeNodeFiles.sh
Due to change in hzn mms object list, edgeNodeFiles.sh needed to change
Fixes #3518 
Tested on a new IEAM install
...
- [x ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.
> Change edgeNodeFiles since hzn mms object list changed behavior

- agreementbot/secure_api.go
- go.mod
- go.sum
- kube_operator/api_objects.go
- kube_operator/client.go
- kube_operator/kubeworker.go
- resource/secret_api.go
> Issue #3445 - Need to support CRD-less kube operators for edge clusters

- agreementbot/agreementbot.go
- agreementbot/governance.go
…n agbotdb changes certificates
...
> Issue 3526 - Bug: agbot needs to restart when agbotdb changes certificates

- test/README.md
- test/gov/run_kube.sh
> update microk8s version in e2edev

- test/docker/Dockerfile
- tools/arch-tag
> update arch-tag script and go version in e2edev

- go.mod
- go.sum
> Issue 3502 - Update anax dependencies

- test/gov/service_upgrading_downgrading_test.sh
- test/gov/utils.sh
> fix e2edev service upgrading/downgrading test

- test/docker/fs/hzn/service/cpu/service.sh
> Issue 3543 - update anax e2edev

- agreementbot/consumer_protocol_handler.go
> Issue #3549 - Bug: agbot panic on nil service policy

- agent-install/agent-install.sh
Add `37` as a supported Fedora version.
Fixes #3556 
Tested successfully on a Fedora 37 aarch64 Raspberry Pi device.
...
> Issue #3556 - Fedora 37 support

- agent-install/agent-install.sh
Add support for RHEL `8.7` and RHEL `9.1` to `agent-install.sh`
Fixes #3560
...
> Issue #3560 - Support RHEL 8.7 and RHEL 9.1 releases

- agent-install/agent-install.sh
- Test architecture for edge cluster 
- Test architecture for anax-in-container install
- Add Centos 9
- Fix issue with adding the config level
Fixes # #3546 
Tested on different architectures for both edge cluster and anax in container
...
- [ x] I have tagged the reviewers in a …
> Issue3546 - check architectures for k8s and anax-in-container

- agent-install/agent-install.sh
> Issue 3565 - Improve robustness of agent-install to retry on errors

- go.mod
- go.sum
> Issue 3502 - Update anax dependency

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 3572 - First message drop for translation for 1Q2023

- cli/exchange/ha_group.go
- cli/register/register.go
> Issue 3540 - Update hzn cli to use HA group member add and remove APIs

- cli/exchange/ha_group.go
- cli/register/register.go
> Issue3525 - Bug: hzn cli changes for listing hagroups

- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 3572 - First message drop for translation for 1Q2023 (part 2)

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/consumer_protocol_handler.go
- agreementbot/governance.go
- agreementbot/persistence/workload_usage.go
- cutil/cutil.go
- events/events.go
- externalpolicy/text_language/text_language_test.go
- policy/policy_file_test.go
- policy/workload.go
- version/version.go
> Issue 3510 - Bug: HA group not honored if deployment policy service stanza is replaced

- agent-install/agent-install.sh
- cli/cliutils/cliutils.go
- cli/exchange/ha_group.go
- cli/fdo/voucher.go
- cli/hzn.go
- cli/sdo/voucher.go
- clusterupgrade/kubeClient.go
- docs/cluster_install.md
> Issue 3522 - Feature Request: FDO support

- agent-install/agent-install.sh
- agent-install/edgeNodeFiles.sh
- [ x] This change requires a documentation update
...
- [ x] My changes generate no new …
> Package work for arm64 Mac support

- agent-install/agent-install.sh
- agent-install/k8s/deployment-template.yml
> Issue 3579 - Bug: agent-install changes for vanilla k8s edge clusters

- cli/fdo/voucher.go
> Issue 3522 - getting node token from the FDO owner service

- agent-install/agent-install.sh
> Issue3594 - Bug: fix agent-install.sh for MacOS amd64

- cli/fdo/voucher.go
> Issue 3522 - handles GET voucher API returning json output

- cli/exchange/ha_group.go
- cli/register/register.go
> Issue 3607 - Bug: edge cluster nodes got into the HA groups

- cli/fdo/key.go
- cli/fdo/voucher.go
- cli/hzn.go
> Issue 3522 - Add command to get public keys

- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
> Issue 3572 - Second message drop for translation for 1Q2023

- agreement/node.go
- agreementbot/consumer_protocol_handler.go
- download/download_worker.go
- exchangesync/user_input.go
> Bug: agreements got canceled because user input changes at registration

- docs/agent_container_manual_deploy.md
- docs/agentfile_manifest.md
- docs/agreement_bot_api.md
- docs/all-in-1-setup.md
- docs/api.md
- docs/attributes.md
- docs/built_in_policy.md
- docs/cluster_install.md
- docs/deployment_policy.md
- docs/deployment_string.md
- docs/index.md
- docs/managed_workloads.md
- docs/model_policy.md
- docs/node_management_overview.md
- docs/node_management_policy.md
- docs/node_management_status.md
- docs/node_policy.md
- docs/policy.md
- docs/properties_and_constraints.md
- docs/service_def.md
Fixes #3615 
Reformat the Anax documentation:
-  include preprocessor directives
-  substitution strings
-  adhere to documentation style
-  codeblocks
-  anchor tags
-  external links
- ToC navigation ordering
- table captions and formatting
...
> Issue3615 reformatdocs

- cli/register/register.go
> Issue3618 - Bug: message at registration should include ha group name

- Makefile
- ess/image/edge-sync-service-arm64/Dockerfile.ubi
> Add ess arm64 image

- agent-install/k8s/deployment-template.yml
> Update deployment-template.yml to resolve errors in ocp

- docs/agent_container_manual_deploy.md
- docs/agentfile_manifest.md
- docs/agreement_bot_api.md
- docs/api.md
- docs/attributes.md
- docs/built_in_policy.md
- docs/deployment_policy.md
- docs/deployment_string.md
- docs/index.md
- docs/managed_workloads.md
- docs/model_policy.md
- docs/node_management_overview.md
- docs/node_management_policy.md
- docs/node_management_status.md
- docs/node_policy.md
- docs/policy.md
- docs/properties_and_constraints.md
- docs/service_def.md
Fixes #3632 
Incorporate several hundred comments by our tech editor
Review all of the pages at https://open-horizon.github.io/docs/anax/docs/
...
> Issue #3632 - incorporate Tech Editor comments

- cli/locales/de/messages.gotext.json
- cli/locales/es/messages.gotext.json
- cli/locales/fr/messages.gotext.json
- cli/locales/it/messages.gotext.json
- cli/locales/ja/messages.gotext.json
- cli/locales/ko/messages.gotext.json
- cli/locales/pt-BR/messages.gotext.json
- cli/locales/zh-CN/messages.gotext.json
- cli/locales/zh-TW/messages.gotext.json
- i18n_translation/translated/anax.out.gotext_es.json
- i18n_translation/translated/anax.out.gotext_it.json
- i18n_translation/translated/anax.out.gotext_zh_TW.json
- i18n_translation/translated/hzn.out.gotext_de.json
- i18n_translation/translated/hzn.out.gotext_es.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_it.json
- i18n_translation/translated/hzn.out.gotext_ja.json
- i18n_translation/translated/hzn.out.gotext_ko.json
- i18n_translation/translated/hzn.out.gotext_pt_BR.json
- i18n_translation/translated/hzn.out.gotext_zh_CN.json
- i18n_translation/translated/hzn.out.gotext_zh_TW.json
- locales/es/messages.gotext.json
- locales/it/messages.gotext.json
- locales/zh-TW/messages.gotext.json
> Issue 3572 - Third translated message drop for 1Q2023

- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el
- go.mod
- go.sum
> Issue3637 - Fix vulnerability

- cli/exchange/business.go
> Issue 3440 - Bug: Confusing error message publishing a deployment policy

- persistence/device.go
> Issue 3644 - Bug: agent could panic if 2.29.0 agent upgrades to 2.30.0

- docs/api.md
- docs/attributes.md
- docs/managed_workloads.md
Fixes https://github.com/open-horizon/open-horizon.github.io/issues/408
- Consistent top level headers
- Consistent indentation
- copyright updates
View these pages at:
- https://open-horizon.github.io/docs/anax/docs/attributes/
- https://open-horizon.github.io/docs/anax/docs/api/
- ~https://open-horizon.github.io/docs/anax/docs/agent_container_manual_deploy/~
- https://open-horizon.github.io/docs/anax/docs/managed_workloads/
> Issue 408 - Consistent top level headers

- docs/ha_groups.md
> Issue #3600 - Documentation: High Availability Node Groups

- docs/ha_groups.md
Fixes #3658 
Review: https://open-horizon.github.io/docs/anax/docs/ha_groups/
> Issue #3658 - Documentation: Editorial corrections to HA Groups

- clusterupgrade/cluster_install_files.go
- test/Makefile
> Issue3637 - Fix vulnerability (part4)

- clusterupgrade/cluster_install_files.go
- clusterupgrade/cluster_upgrade_worker.go
- container/container.go
> Issue #3663 - Bug: unhandled errors found by static scan

- agent-install/edgeNodeFiles.sh
> Issue 3522 - add HZN_FDO_SVC_URL in agent-install.cfg file

- Makefile
- go.mod
- go.sum
> Update edge sync service version to 1.9.9

- docs/all-in-1-setup.md
Added `/docs` prefix to mgmt-hub link to fix broken link.
Fixes #3668 and open-horizon.github.io#394
...
@johnwalicki FYI
This should close #3668
> Issue-3668: Fixed broken link to mgmt-hub page

- api/api_publickey.go
- cli/cliconfig/config.go
- cli/cliutils/cliutils.go
- cli/cliutils/stdout_logging.go
- cli/exchange/service.go
- cli/sdo/voucher.go
- cli/sync_service/object.go
- cli/sync_service/sync_service.go
- cli/unregister/unregister.go
- cutil/cutil.go
- helm/client.go
- imagefetch/imagepull.go
> Issue #3667 - Bug: check error on deferred file close

- Makefile
- go.mod
- go.sum
> Update Sync Service to 1.9.10

- docs/agent_container_manual_deploy.md
> Anax in container

- version/version.go
> Updated the PREFERRED_EXCHANGE_VERSION to 2.109.0

- version/version.go
> Updated the PREFERRED_EXCHANGE_VERSION to 2.109.1

- docs/agent_container_manual_deploy.md
Fixes #3681 
Move the prereqs section up.
Visit https://open-horizon.github.io/docs/anax/docs/agent_container_manual_deploy/
> Issue #3681 - Documentation: anax-in-container prereqs

- docs/agent_container_manual_deploy.md
Fixes #3681 
Fix MacOS substitution strings
> Issue3681 macos

- version/version.go
> Updated the PREFERRED_EXCHANGE_VERSION to 2.109.2

- version/version.go
> Updated the PREFERRED_EXCHANGE_VERSION to 2.110.0

- version/version.go
> Updated the PREFERRED_EXCHANGE_VERSION to 2.110.1

- docs/all-in-1-setup.md
Simple link fix.
Fixes #3696 
...
> Issue-3696: Fixed broken link

- docs/agent_container_manual_deploy.md
> Fix anax in container doc

- test/docker/fs/hzn/service/usehello/Dockerfile
> Update usehello service to use curl<7.88.0

- docs/agent_container_manual_deploy.md
> Issue #3707 - Documentation: anax-in-container grammar suggestions

- MAINTAINERS.md
> Add Doug to maintainers

- .github/workflows/anax-build-test.yml
- Makefile
Updated to new version
Fixes #3731
> Issue 3731 - Updated version to 2.31.0

- anax-in-container/horizon-container
> Add -r to unregister on stop

- docs/all-in-1-setup.md
This fixes two broken links on the /anax/all-in-1-setup/ docs page.
Fixes #open-horizon.github.io/491
...
@dlarson04 and @johnwalicki this fixes the broken links issue 491 in docs.
> Issue-491: Fixes the documentation broken links issue

- api/path_node.go
- exchangesync/node.go
- test/docker/fs/hzn/service/usehello/Dockerfile
> Issue3748 - MultiNamespace: Set node clusterNamespace in exchange

- Makefile
- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- anax-in-container/Dockerfile.ubi.ppc64el
- anax-in-container/Dockerfile.ubi.s390x
- anax-in-container/Dockerfile_agbot.ubi
- anax-in-k8s/Dockerfile.ubi.amd64
- anax-in-k8s/Dockerfile.ubi.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.amd64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el
- anax-in-k8s/Dockerfile.ubi.ppc64el
- css/image/cloud-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-arm64/Dockerfile.ubi
- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
- ess/image/edge-sync-service-s390x/Dockerfile.ubi
- test/gov/run_kube.sh
Rebase all of the Dockerfile.ubi files to ubi9/ubi-minimal:9.1
Fixes #3628
...
> Issue3628 rebasedockerfiles

- kube_operator/api_objects.go
- kube_operator/client.go
> Issue #3759 - Bug: operator failed to deploy in non-default namespace

- api/path_node.go
- exchangesync/node.go
> Issue3758 - Bug: panic after agent restart

- kube_operator/api_objects.go
> Issue #3763 - Bug: cluster agent removes own namespace

- agent-install/agent-install.sh
- agent-install/agent-uninstall.sh
- agent-install/k8s/role.yml
> remove multi-namespace in agent install

- go.mod
- go.sum
> Issue 3777 - Fix dependency vulnerability

- agent-install/agent-install.sh
> Issue 3781 - Support agent on Redhat 8.8

- go.mod
- go.sum
> Issue 3777 (part2) - Fix dependency vulnerability

- agent-install/agent-install.sh
> Issue #3783 - agent-install.sh Add support for Fedora 38

- anax-in-container/Dockerfile.ubi.s390x
Per [this comment](https://github.com/open-horizon/anax/issues/3628#issuecomment-1559980491), this PR is to fix the typo
...
> Fix typo in Dockerfile.ubi.s390x

- agent-install/edgeNodeFiles.sh
> fix edgeNodeFiles.sh

- agent-install/agent-install.sh
> Issue 3795 - Bug: Edge cluster agent failed during re-install

- pkg/rpm/horizon/horizon.spec
> Issue 3789 - Horizon rpm package is installing podman when it should not

- pkg/deb/Makefile
- pkg/mac/Makefile
- pkg/rpm/horizon-cli/Makefile
> Issue 3802 - Add role.yml to package files

- anax-in-container/horizon-container
- pkg/deb/horizon/DEBIAN/postinst
- pkg/rpm/horizon/horizon.spec
> Issue 3790 - Cron job creation fails if directory does not exist

- agent-install/agent-install.sh
Update architecture for agent device support. Add s390x. 
#3647 
Tested on Ubuntu and RHEL agent-install for device
...
> update device support for s390x

- cutil/cluster.go
- externalpolicy/builtin_properties.go
…_SCOPED“ in built-in property
...
> Issue open-horizon#3813 - MultiNamespace: Agent should add “openhorizon.kubernetesNamespaceScoped" in built-in property

- test/gov/gov-combined.sh
- test/gov/hzn_reg.sh
> add settoken test case in e2edev

- Makefile
- agent-install/agent-install.sh
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.s390x
- anax-in-k8s/Dockerfile.ubi.s390x
Update architecture for agent cluster support. Add s390x.
Fixes #3647 
Changes based on suggestions from @dlarson04 
Tested on microk8s on ubuntu on s390x
...
> update cluster support for s390x

- api/path_node_policy_test.go
- exchangesync/node_policy_test.go
- producer/producer_protocol_handler.go
> fix unit test

- .github/scripts/docker_build_script.sh
- .github/scripts/docker_push_script.sh
- .github/scripts/package_push.sh
- .github/workflows/build-push.yml
- Added support for s390x artifacts being built with our GitHub action workflow
Fixes #3828 
- Tested workflow run, confirmed proper docker images were created and proper packages were created
- s390x RPM package install tested
...
> Issue #3828 - Feature Request: Add s390x support for Github CI action

- test/gov/hzn_dev_services.sh
> Fix e2edev since docker build message is changed

- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- anax-in-container/Dockerfile.ubi.ppc64el
- anax-in-container/Dockerfile.ubi.s390x
- anax-in-container/Dockerfile_agbot.ubi
- anax-in-k8s/Dockerfile.ubi.amd64
- anax-in-k8s/Dockerfile.ubi.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.amd64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.s390x
- anax-in-k8s/Dockerfile.ubi.ppc64el
- anax-in-k8s/Dockerfile.ubi.s390x
- css/image/cloud-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-arm64/Dockerfile.ubi
- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
- ess/image/edge-sync-service-s390x/Dockerfile.ubi
Fixes #3852 
- Issue #3852 - Remove unused DOCKER_VER argument from Dockerfile_agbot.ubi
- Issue #3852 - Bump to Docker Engine version 24.0.5
- Issue #3852 - Update container images to UBI 9.2
I don't have the infrastructure to test these changes.  After the build process, this should be tested.
> Issue3852 ubi92rebase

- .github/scripts/docker_push_script.sh
- .github/scripts/package_push.sh
- .github/workflows/build-push.yml
Updated GHA and scripts to support appending branch name to testing tag images
Fixes #3868
...
> Issue #3868 - Updated GHA and scripts to support appending branch name

- anax-in-container/Dockerfile.ubi.ppc64el
Updated to use correct path for UBI9 base image for PPC64
Fixes #3870 
...
> Issue #3870 - Updated baseimage path for UBI9

- go.mod
- go.sum
> gUpdate dep 2.30

- .github/scripts/configure_versions_script.sh
Added missing script for GitHub Action to execute build and push.
Fixes #3872 
...
> Issue #3872 - Added GHA from master

- agent-install/edgeNodeFiles.sh
Added the variables to push s390x architectures into CSS
Fixes # https://github.com/open-horizon/anax/issues/3830
Tested against a 2.30.0-1429 build that had s390x components
...
> Add s390x to edgeNodeFiles

- cli/exchange/business.go
- compcheck/secretbinding_check.go
- exchangecommon/secret.go
> Issue open-horizon#3716 - NodeSecret: pattern and policy CLI checks node secret

- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el
- anax-in-k8s/Dockerfile.ubi.ppc64el
- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
Updated all ppc64el Dockerfiles to use correct UBI9 base image path
Fixes #3870 
...
> Issue #3870 - Updated all ppc64el Dockerfiles to use correct UBI9 base image path

- docs/agentfile_manifest.md
- docs/node_management_overview.md
Embedded YouTube video showing agent auto-upgrade feature in two documentation pages:
- https://open-horizon.github.io/docs/anax/docs/agentfile_manifest/
- https://open-horizon.github.io/docs/anax/docs/node_management_overview/
Fixes #3875 
...
@johnwalicki I'll need to confirm that it is working properly once the pages are merged and the CopyDocs GHA has run.
> Issue-3875: Embedded video into docs for agent auto-upgrade feature

- agreementbot/agreementworker.go
- cli/exchange/business.go
- cli/exchange/pattern.go
- compcheck/secretbinding_check.go
- kube_operator/api_objects.go
- kube_operator/kubeworker.go
> Issue open-horizon#3718 - NodeSecret: hzn deploycheck checks node secret

- agreementbot/secrets/secrets.go
- agreementbot/secure_api.go
- docs/agbot_secure_api.json
> Issue 3721 - NodeSecret: documentation

- container/container.go
> open-horizon#3931 - Bug: e2edev failed since move to Docker 24.0.7

- agreementbot/agreementbot.go
- agreementbot/agreementworker.go
- agreementbot/basic_agreement_worker.go
- agreementbot/basic_protocol_handler.go
- agreementbot/consumer_protocol_handler.go
> Issue3938 - Bug: node doesn't get proposal after change node policy on the exchange

- .github/workflows/E2E-test.yml
- .github/workflows/build-push.yml
- go.mod
- go.sum
- test/Makefile
- test/README.md
- test/docker/Dockerfile
Updated Github Actions to use Golang 1.21. Also added `workflow_dispatch` as a build trigger to allow us to manually build and push the artifacts.
Fixes #3929
...
> Issue 3929 - Updated build to use latest Golang 1.21

- .github/workflows/E2E-test.yml
- .github/workflows/build-push.yml
- container/container.go
- go.mod
- go.sum
- test/Makefile
- test/README.md
- test/docker/Dockerfile
> Issue 3929 - Updated build to use latest Golang 1.21. Cherry-pick to v2.30

- agreementbot/governance.go
- agreementbot/persistence/postgresql/secrets.go
- agreementbot/secret_updater.go
> Bug - node level secret update not recieved intermitently

- agreementbot/basic_protocol_handler.go
- agreementbot/consumer_protocol_handler.go
> Issue3949 - Bug: Agbot panic after receiving several rejection reply

- agent-install/agent-install.sh
> Bug: remove hard-coded namespace in agent-install.sh

- agent-install/agent-install.sh
> fix AgentInstall error message

- agent-install/edgeNodeFiles.sh
Restructured to allow this to be used with all-in-one hubs by removing the dependency on `oc` when not needed
Tested in all-in-one hub
...
> edgeNodeFiles for allinone

- agent-install/agent-install.sh
- agent-install/k8s/auto-upgrade-cronjob-template.yml
- agent-install/k8s/deployment-template.yml
- anax-in-k8s/Dockerfile.ubi.amd64
- anax-in-k8s/config/anax.json
- anax-in-k8s/script/anax.service
- clusterupgrade/cluster_install_files.go
- clusterupgrade/cluster_upgrade_worker.go
- clusterupgrade/kubeClient.go
> Issue 3969, 3970 - NFS volume permission issue, auto-upgrade with remote ICR

- agent-install/agent-install.sh
> Add RHEL9.3 and bookworm debian support

- .github/workflows/build-push.yml
Fixes #4002 
- Ran in fork v2.30 branch to ensure Mac cli is created.
- Exact same feature that was added to master branch.
...
> Issue #4002 - Feature Request: Actions Workflow MacOS M1 Runner v2.30

- agreementbot/secret_updater_test.go
- events/secret_events_test.go
- policy/workload.go
- policy/workload_test.go
> Issue #4009 - Fix unit tests

- agent-install/agent-install.sh
Just modified that one env var to add arm64.  Found no other lines to change.
Fixes #3740 
...
@LiilyZhang and @dlarson04 this was a tiny change.
> Added arm64 to SUPPORTED_EDGE_CLUSTER_ARCH

- agreementbot/api.go
- api/api.go
> Issue 4022 - Bug: Set CORS header in node api

- agent-install/agent-uninstall.sh
> Fix agent uninstall if some special chars in the password

- .github/workflows/E2E-test.yml
- .github/workflows/build-push.yml
- Makefile
Updating master to new version 2.32.0.
> Updated version to v2.32.0

- exchangecommon/node_management_policy.go
- nodemanagement/agent_upgrade.go
- nodemanagement/node_management_worker.go
> Issue 3986 - AgentImageCleanup: Agent handles new type of NMP

- .github/workflows/E2E-test.yml
- .github/workflows/build-push.yml
Added branch to gh actions.
Fixes #4049 
...
> Issue 4049 - Fix builds for v2.31 branch

- test/gov/run_kube.sh
> fix microk8s on e2edev

- go.mod
- go.sum
> Upgrade golang net package

- agreement/agreement.go
> Agent cancels agreement after built-in property change

- test/docker/Dockerfile
- test/gov/sync_service_test.sh
> Update the e2edev-test container's base os from ubuntu 18.04 to 22.04

- clusterupgrade/cluster_install_files.go
> Issue 4084 - Bug: failed to create k8s image tar file

- clusterupgrade/cluster_install_files.go
- test/docker/Dockerfile
- test/gov/run_kube.sh
- test/gov/sync_service_test.sh
> Cherry-pick a fix for cluster auto-upgrade

- agent-install/agent-install.sh
> Issue 4078 - support agent install on newer os's (ubuntu 24.04, RH 9.4)

- docs/cluster_install.md
Fixes #4091 
...
@open-horizon/documentation-working-group
> Issue 4091: changed YML to YAML

- cli/cliutils/cliutils.go
Set hzn CLI to trust system CA's like the anax agent can
Fixes #4099 
Tested on macos and linux
...
> Add system CAs for CLI

- cli/cliutils/cliutils.go
> Cherry-pick to Add system CAs for CLI

- go.mod
- go.sum
> Upgrade github.com/docker/docker version to v27.1.1

- cli/kube_deployment/kube_deployment.go
> Issue open-horion#4098 - Bug: Change "pvcSize" to "pvcSizeGB"

- agent-install/edgeNodeFiles.sh
Fixes  https://github.com/open-horizon/anax/issues/4138
Pushed just EdgeCluster agent with edgeNodeFiles and saw the correct manifest was created
...
> Make sure software version is set

- Makefile
- go.mod
- go.sum
> Update Anax to use sync service v1.11.3

- agreement/agreement.go
> Issue open-horizon#4158 - Bug: Intermittent panic on agent startup

- anax-in-container/Dockerfile_agbot.ubi
- go.mod
- go.sum
The PR includes fixed for vulnerabilities listed in the below issue.
Fixes #4176
Could not test it, because I need an image with the changes to be built by GH Actions pipeline in order to be able to run Aquasec scan on it.
> Fix vulnerabilities in amd64_agbot image

- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- go.mod
- go.sum
The PR includes fixed for vulnerabilities listed in the below issue.
Fixes #4172 
Could not test it, because I need an image with the changes to be built by GH Actions pipeline in order to be able to run Aquasec scan on it.
> Issue open-horizon#4172 - Fix vulnerabilities in multiple images for v2.31

- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- go.mod
- go.sum
The PR includes fixed for vulnerabilities listed in the below issue.
Fixes #4172 
Could not test it, because I need an image with the changes to be built by GH Actions pipeline in order to be able to run Aquasec scan on it.
> Issue open-horizon#4172 - Fix vulnerabilities in multiple images

- .github/workflows/build-push.yml
> Issue openhorizon#4197 - Update GitHub Actions workflows

- anax-in-container/Dockerfile.ubi.amd64
The PR includes fixed for vulnerabilities listed in the below issue.
Fixes #4205 
Could not test it, because I need an image with the changes to be built by GH Actions pipeline in order to be able to run Aquasec scan on it.
> Issue #4205 - Update docker version in amd64_anax to 26.1.4

- agent-install/agent-install.sh
Update to agent-install.sh
Fixes #4215 
Installed on new RHEL version
...
> Add new RHEL and Fedora releases

- agent-install/agent-install.sh
> Issue open-horizon#4216 - Add new RHEL and Fedora releases

- anax-in-container/Dockerfile.alpine.amd64
- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- anax-in-container/Dockerfile.ubi.ppc64el
- anax-in-container/Dockerfile.ubi.s390x
- anax-in-container/Dockerfile_agbot.ubi
- anax-in-k8s/Dockerfile.ubi.amd64
- anax-in-k8s/Dockerfile.ubi.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.amd64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.s390x
- anax-in-k8s/Dockerfile.ubi.ppc64el
- anax-in-k8s/Dockerfile.ubi.s390x
- css/image/cloud-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-arm64/Dockerfile.ubi
- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
- ess/image/edge-sync-service-s390x/Dockerfile.ubi
Reverts open-horizon/anax#4228
> Revert "Use ubi-micro instead of ubi-minimal to reduce the threat surface attack area."

- Makefile
> Issue open-horizon#4236 - fix make i18n-catalog command

- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- anax-in-container/Dockerfile.ubi.ppc64el
- anax-in-container/Dockerfile.ubi.s390x
- anax-in-container/Dockerfile_agbot.ubi
- anax-in-k8s/Dockerfile.ubi.amd64
- anax-in-k8s/Dockerfile.ubi.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.amd64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.s390x
- anax-in-k8s/Dockerfile.ubi.ppc64el
- anax-in-k8s/Dockerfile.ubi.s390x
- css/image/cloud-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-amd64/Dockerfile.ubi
- ess/image/edge-sync-service-arm64/Dockerfile.ubi
- ess/image/edge-sync-service-ppc64el/Dockerfile.ubi
- ess/image/edge-sync-service-s390x/Dockerfile.ubi
Issue #4227 - Update container images to latest UBI base image
Fixes # ( #4227)
**make ...-docker**
> Issue #4227 - Update container images to latest UBI base image

- Makefile
> Issue open-horizon#4245 - Bug: Fix 'make $(TMPGOPATH)/bin/gotext' target

- Makefile
> update CSS/ESS version to use v.1.11.5

- Makefile
- go.mod
- go.sum
> update CSS/ESS version in anax 2.30 branch

- Makefile
- go.mod
- go.sum
> update CSS/ESS version in anax 2.31 branch

- go.mod
- go.sum
Updated golang/glog version to v1.2.4 in order to fix vulnerabilities found during twistlock scan
- [ +] Bug fix (non-breaking change which fixes an issue)
...
- [+ ] My code follows the style guidelines of this project
- [+ ] I have performed a self-review of my own code
- [+ ] My changes generate no new warnings
- [ +] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.
> Update golang/glog version to v1.2.4

- Makefile
- go.mod
- go.sum
> Upgrade sync service version to v1.11.6

- Makefile
- go.mod
- go.sum
> update sync service version to v1.11.7

- Makefile
- go.mod
- go.sum
> update sync service version to v1.10.3

- Makefile
> fix arch in k8s cronjob image

- .github/workflows/copydocs.yml
- agent-install/README.md
Fixes #4300 
- Removes unsuccessful copy from copydocs.yml
- Adds directives to README
- Fix some markdown, grammar, supported version issues
...
> Copy agent-install readme to Docs repo

- go.mod
- go.sum
update golang-jwt/jwt/v4 to v4.5.2
...
> update golang-jwt/jwt/v4 to v4.5.2

- .github/workflows/E2E-test.yml
- .github/workflows/build-push.yml
- test/gov/run_kube.sh
Update Ubuntu 20.04 to a supported version. 
[4312](https://github.com/open-horizon/anax/issues/4312])
> Issue open-horizon#4312 - Update Ubuntu Version in GitHub Actions Workflows

- cli/locales/fr/messages.gotext.json
- i18n_translation/anax.out.gotext.json
- i18n_translation/hzn.out.gotext.json
- i18n_translation/original/anax.out.gotext.json.auto
- i18n_translation/original/hzn.out.gotext.json.auto
- i18n_translation/translated/anax.out.gotext_fr.json
- i18n_translation/translated/hzn.out.gotext_fr.json
- locales/fr/messages.gotext.json
> Issue open-horizon#4305 - Translation: First 2.31 translation drop

- go.mod
- go.sum
Update the library because there was a vulnerability found in twistlock and newer version is no longer vulnerable
...
> bump golang.org/x/oauth2 to v0.27.0

- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.amd64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.arm64
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.ppc64el
- anax-in-k8s/Dockerfile.ubi.auto-upgrade-cron.s390x
Bump kubectl to v1.33.0 this version is not vulnarable like the previous
...
> bump kubectl to v1.33.0

- docs/agent_container_manual_deploy.md
- docs/agent_in_multi_namespace.md
- docs/agentfile_manifest.md
- docs/agreement_bot_api.md
- docs/all-in-1-setup.md
- docs/api.md
- docs/attributes.md
- docs/built_in_policy.md
- docs/cluster_install.md
- docs/deployment_policy.md
- docs/deployment_string.md
- docs/ha_groups.md
- docs/index.md
- docs/managed_workloads.md
- docs/model_policy.md
- docs/node_management_overview.md
- docs/node_management_policy.md
- docs/node_management_status.md
- docs/node_policy.md
- docs/policy.md
- docs/properties_and_constraints.md
- docs/secrets.md
- docs/service_def.md
This PR updates the front matter in documentation files to use the correct copyright statement, update lastupdated dates, and update years fields.
> Issue 4333: Update front matter in documentation files

- .github/workflows/E2E-test.yml
- test/gov/run_kube.sh
> Update OS CI and microK8s for the fresh version

- anax-in-container/Dockerfile.ubi.amd64
- anax-in-container/Dockerfile.ubi.arm64
- anax-in-container/Dockerfile.ubi.ppc64el
- anax-in-container/Dockerfile.ubi.s390x
Update the anax docker images to the fresh version 27.5.1.
Local tests.
> Update the anax docker images to the fresh version

- test/Makefile
- test/gov/start_mgmt_hub.sh
References: #4345
Changes:
- Unlocked the docker image version tag env var for the Exchange.
- Unlocked the log level env var for the Exchange.
1) Set new known good value for either variable.
2) Run E2E test runner.
...
> Issue-4345: Unlocked Exchange Environmental  Variables in E2E Test Runner

- agreementbot/api.go
- cli/secrets_manager/secrets_manager.go
> Issue open-horizon#4249 - Fix CWE-79: Cross-Site Scripting

- cli/exchange/apikey.go
- cli/exchange/user.go
- cli/hzn.go
- test/gov/hzn_apikey.sh
The hzn exchange user CLI command is extended with a set of dedicated subcommands:
hzn exchange user list subcommand is extended with new apikeys attribute (similarly to REST API).
hzn exchange user createkey subcommand is added - it executes POST /v1/orgs/<org>/users/<user>/apikeys call with payload { description: <description> }
hzn exchange user getkey subcommand is added - it executes GET /v1/orgs/<org>/users/<user>/apikeys/<keyid>
hzn exchange user removekey subcommand is added - it executes DELETE /v1/orgs/<org>/users/<user>/apikeys/<keyid>
Manually test the commands above.
...
> add apikey support subcommands for hzn exchange user CLI command

- Makefile
- go.mod
- go.sum
> Update Sync Service to v1.11.8

- agent-install/agent-install.sh
> Issue open-horizon#4397 - Bug: agent-install failing on Debian 11

- agent-install/edgeNodeFiles.sh
> feat: 1673 cert override name for edgeNodeFiles

- agreementbot/secrets/secrets.go
- agreementbot/secure_api.go
- docs/agbot_secure_api.json
Update swagger so it has less errors
Fixes #4406 
...
> Update swagger in anax
